<?php defined('BASEPATH') || exit('No direct script access allowed');

/**
 * Migration pengadaan obat (§16).
 *
 * Alasan tabel tambahan:
 * - supplier            : data pemasok obat (sumber pengadaan).
 * - pengadaan_obat (+detail) : pesanan pembelian ke supplier (status Dipesan).
 * - penerimaan_obat (+detail) : penerimaan barang + cek kesesuaian per item.
 *   Penerimaan berstatus Sesuai menambah stok_obat dan mencatat mutasi_stok.
 * - retur_pengadaan (+detail) : retur/komplain barang yang Tidak sesuai.
 */
class Migration_pengadaan extends Migration
{
    public function up()
    {
        $this->db->query("CREATE TABLE IF NOT EXISTS supplier (
            id_supplier BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            kode_supplier VARCHAR(50) NOT NULL UNIQUE,
            nama_supplier VARCHAR(150) NOT NULL,
            alamat TEXT,
            no_hp VARCHAR(20),
            status VARCHAR(20) NOT NULL DEFAULT 'AKTIF',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )");

        $this->db->query("CREATE TABLE IF NOT EXISTS pengadaan_obat (
            id_pengadaan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nomor_pengadaan VARCHAR(50) NOT NULL UNIQUE,
            id_supplier BIGINT NOT NULL REFERENCES supplier(id_supplier),
            tanggal_pesanan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            total NUMERIC NOT NULL DEFAULT 0,
            status VARCHAR(30) NOT NULL DEFAULT 'Dipesan',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )");

        $this->db->query("CREATE TABLE IF NOT EXISTS pengadaan_obat_detail (
            id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_pengadaan BIGINT NOT NULL REFERENCES pengadaan_obat(id_pengadaan) ON DELETE CASCADE,
            id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
            jumlah_pesan INTEGER NOT NULL,
            harga NUMERIC NOT NULL,
            subtotal NUMERIC NOT NULL
        )");

        $this->db->query("CREATE TABLE IF NOT EXISTS penerimaan_obat (
            id_penerimaan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_pengadaan BIGINT NOT NULL REFERENCES pengadaan_obat(id_pengadaan),
            nomor_penerimaan VARCHAR(50) NOT NULL UNIQUE,
            tanggal_terima TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            status VARCHAR(30) NOT NULL DEFAULT 'Sesuai',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )");

        $this->db->query("CREATE TABLE IF NOT EXISTS penerimaan_obat_detail (
            id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_penerimaan BIGINT NOT NULL REFERENCES penerimaan_obat(id_penerimaan) ON DELETE CASCADE,
            id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
            jumlah_terima INTEGER NOT NULL,
            kondisi VARCHAR(30) NOT NULL DEFAULT 'Baik'
        )");

        $this->db->query("CREATE TABLE IF NOT EXISTS retur_pengadaan (
            id_retur BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_penerimaan BIGINT NOT NULL REFERENCES penerimaan_obat(id_penerimaan),
            nomor_retur VARCHAR(50) NOT NULL UNIQUE,
            tanggal_retur TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            status VARCHAR(30) NOT NULL DEFAULT 'Diajukan',
            keterangan TEXT,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )");

        $this->db->query("CREATE TABLE IF NOT EXISTS retur_pengadaan_detail (
            id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_retur BIGINT NOT NULL REFERENCES retur_pengadaan(id_retur) ON DELETE CASCADE,
            id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
            jumlah INTEGER NOT NULL,
            alasan TEXT
        )");
    }

    public function down()
    {
        foreach (array(
            'retur_pengadaan_detail', 'retur_pengadaan',
            'penerimaan_obat_detail', 'penerimaan_obat',
            'pengadaan_obat_detail', 'pengadaan_obat', 'supplier',
        ) as $table) {
            $this->db->query("DROP TABLE IF EXISTS {$table}");
        }
    }
}
