<?php defined('BASEPATH') || exit('No direct script access allowed');

/**
 * Migration apotek online pasien (GO/ADJUST).
 *
 * - pesanan_online + pesanan_online_detail: konsep pesanan online
 *   (tidak ada di existing). Cart tetap session (tanpa tabel).
 * - penjualan jenis ONLINE: CHECK diperluas (RESEP/LANGSUNG utuh).
 * - Semua statement idempoten (IF NOT EXISTS / DO-guard) agar aman
 *   dijalankan di database lama maupun baru.
 */
class Migration_apotek_online extends Migration
{
    public function up()
    {
        $this->db->query("CREATE TABLE IF NOT EXISTS pesanan_online (
            id_pesanan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_pasien BIGINT NOT NULL REFERENCES pasien(id_pasien) ON UPDATE CASCADE ON DELETE RESTRICT,
            id_penjualan BIGINT REFERENCES penjualan_obat(id_penjualan) ON UPDATE CASCADE ON DELETE RESTRICT,
            id_tagihan BIGINT REFERENCES tagihan(id_tagihan) ON UPDATE CASCADE ON DELETE RESTRICT,
            nomor_pesanan VARCHAR(50) NOT NULL UNIQUE,
            tanggal_pesanan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            alamat_kirim TEXT NOT NULL,
            total NUMERIC(15,2) NOT NULL DEFAULT 0,
            status VARCHAR(20) NOT NULL DEFAULT 'MENUNGGU',
            status_bayar VARCHAR(20) NOT NULL DEFAULT 'BELUM_DIBAYAR',
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT chk_pesanan_status CHECK (status IN ('MENUNGGU','DIVERIFIKASI','DIPROSES','SIAP','SELESAI','BATAL')),
            CONSTRAINT chk_pesanan_bayar CHECK (status_bayar IN ('BELUM_DIBAYAR','LUNAS','BATAL')),
            CONSTRAINT chk_pesanan_total CHECK (total >= 0)
        )");
        $this->db->query("CREATE TABLE IF NOT EXISTS pesanan_online_detail (
            id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_pesanan BIGINT NOT NULL REFERENCES pesanan_online(id_pesanan) ON UPDATE CASCADE ON DELETE CASCADE,
            id_obat BIGINT NOT NULL REFERENCES obat(id_obat) ON UPDATE CASCADE ON DELETE RESTRICT,
            id_resep BIGINT REFERENCES resep(id_resep) ON UPDATE CASCADE ON DELETE RESTRICT,
            jumlah INTEGER NOT NULL,
            harga NUMERIC(15,2) NOT NULL,
            subtotal NUMERIC(15,2) NOT NULL,
            CONSTRAINT chk_pesanan_detail_jumlah CHECK (jumlah > 0),
            CONSTRAINT chk_pesanan_detail_harga CHECK (harga >= 0),
            CONSTRAINT chk_pesanan_detail_subtotal CHECK (subtotal >= 0)
        )");
        $this->db->query("CREATE INDEX IF NOT EXISTS idx_pesanan_pasien ON pesanan_online(id_pasien)");
        $this->db->query("CREATE INDEX IF NOT EXISTS idx_pesanan_status ON pesanan_online(status)");
        $this->db->query("CREATE INDEX IF NOT EXISTS idx_pesanan_tanggal ON pesanan_online(tanggal_pesanan)");
        $this->db->query("CREATE INDEX IF NOT EXISTS idx_pesanan_detail_pesanan ON pesanan_online_detail(id_pesanan)");

        // Perluas jenis penjualan: ONLINE (RESEP/LANGSUNG tidak berubah).
        $this->db->query("DO \$\$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_jenis_penjualan') THEN
                ALTER TABLE penjualan_obat DROP CONSTRAINT chk_jenis_penjualan;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_jenis_penjualan') THEN
                ALTER TABLE penjualan_obat ADD CONSTRAINT chk_jenis_penjualan
                CHECK (jenis_penjualan IN ('RESEP','LANGSUNG','ONLINE'));
            END IF;
        END \$\$;");
        $this->db->query("DO \$\$ BEGIN
            IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_penjualan_resep_relation') THEN
                ALTER TABLE penjualan_obat DROP CONSTRAINT chk_penjualan_resep_relation;
            END IF;
            IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_penjualan_resep_relation') THEN
                ALTER TABLE penjualan_obat ADD CONSTRAINT chk_penjualan_resep_relation
                CHECK ((jenis_penjualan = 'RESEP' AND id_resep IS NOT NULL) OR (jenis_penjualan IN ('LANGSUNG','ONLINE')));
            END IF;
        END \$\$;");
    }

    public function down()
    {
        $this->db->query("DROP TABLE IF EXISTS pesanan_online_detail");
        $this->db->query("DROP TABLE IF EXISTS pesanan_online");
    }
}
