<?php defined('BASEPATH') || exit('No direct script access allowed');

/** Histori retur penjualan; satu penjualan hanya dapat diretur sekali. */
class Migration_retur_penjualan extends Migration
{
    public function up()
    {
        $this->db->query("CREATE TABLE IF NOT EXISTS retur_penjualan (
            id_retur BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_penjualan BIGINT NOT NULL UNIQUE REFERENCES penjualan_obat(id_penjualan),
            nomor_retur VARCHAR(50) NOT NULL UNIQUE,
            tanggal_retur TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            keterangan TEXT
        )");
        $this->db->query("CREATE TABLE IF NOT EXISTS retur_penjualan_detail (
            id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_retur BIGINT NOT NULL REFERENCES retur_penjualan(id_retur) ON DELETE RESTRICT,
            id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
            jumlah INTEGER NOT NULL CHECK (jumlah > 0),
            UNIQUE (id_retur, id_obat)
        )");
    }

    public function down()
    {
        $this->db->query('DROP TABLE IF EXISTS retur_penjualan_detail');
        $this->db->query('DROP TABLE IF EXISTS retur_penjualan');
    }
}
