<?php defined('BASEPATH') || exit('No direct script access allowed');

/** Retur apotek online (full-order). Satu pesanan hanya punya satu retur aktif;
 * retur DITOLAK boleh diajukan ulang. Stok hanya bergerak saat disetujui. */
class Migration_retur_online extends Migration
{
    public function up()
    {
        $this->db->query("CREATE TABLE IF NOT EXISTS retur_online (
            id_retur BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_pesanan BIGINT NOT NULL REFERENCES pesanan_online(id_pesanan) ON DELETE RESTRICT,
            nomor_retur VARCHAR(50) NOT NULL UNIQUE,
            status VARCHAR(20) NOT NULL DEFAULT 'DIMINTA' CHECK (status IN ('DIMINTA','SELESAI','DITOLAK')),
            alasan TEXT NOT NULL,
            catatan_apoteker TEXT,
            metode_refund VARCHAR(20) CHECK (metode_refund IN ('TUNAI','TRANSFER','E_WALLET','LAINNYA')),
            nominal_refund NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (nominal_refund >= 0),
            tanggal_pengajuan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            tanggal_keputusan TIMESTAMP,
            diproses_oleh BIGINT REFERENCES users(id_user),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )");
        $this->db->query("CREATE TABLE IF NOT EXISTS retur_online_detail (
            id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_retur BIGINT NOT NULL REFERENCES retur_online(id_retur) ON DELETE RESTRICT,
            id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
            jumlah INTEGER NOT NULL CHECK (jumlah > 0),
            disposisi VARCHAR(20) CHECK (disposisi IN ('RESTOCK','MUSNAH')),
            UNIQUE (id_retur, id_obat)
        )");
    }

    public function down()
    {
        $this->db->query('DROP TABLE IF EXISTS retur_online_detail');
        $this->db->query('DROP TABLE IF EXISTS retur_online');
    }
}
