<?php defined('BASEPATH') || exit('No direct script access allowed');

/**
 * Sistem persediaan end-to-end (aditif, tanpa merusak flow lama):
 * - obat: kategori/sediaan/kandungan/produsen/supplier-utama/harga_satuan/harga_jual
 * - permintaan_pengadaan (+detail +log status) + PO boleh merujuk permintaan
 * - penerimaan: surat jalan/faktur/penerima/catatan + status_konfirmasi (lama = DIKONFIRMASI)
 * - retur_pengadaan: pemutus + batch/ED per item (Diajukan lama -> DIAJUKAN)
 * - stok_batch (multi-batch per obat) + mutasi diperkaya (batch/saldo/user)
 * - permission persediaan -> role pemilik kelola_pengadaan
 */
class Migration_sistem_persediaan extends Migration
{
    public function up()
    {
        // 1. Master obat: kolom deskriptif + harga satuan/jual (backfill = harga lama).
        $this->db->query("ALTER TABLE obat
            ADD COLUMN IF NOT EXISTS kategori character varying(100),
            ADD COLUMN IF NOT EXISTS bentuk_sediaan character varying(100),
            ADD COLUMN IF NOT EXISTS kandungan character varying(200),
            ADD COLUMN IF NOT EXISTS produsen character varying(150),
            ADD COLUMN IF NOT EXISTS id_supplier_utama BIGINT REFERENCES supplier(id_supplier),
            ADD COLUMN IF NOT EXISTS harga_satuan NUMERIC(15,2) NOT NULL DEFAULT 0,
            ADD COLUMN IF NOT EXISTS harga_jual NUMERIC(15,2) NOT NULL DEFAULT 0");
        $this->db->query('UPDATE obat SET harga_satuan = harga WHERE harga_satuan = 0');
        $this->db->query('UPDATE obat SET harga_jual = harga WHERE harga_jual = 0');

        // 2. Permintaan pengadaan + detail + histori status (dibuat dulu karena di-FK PO).
        $this->db->query("CREATE TABLE IF NOT EXISTS permintaan_pengadaan (
            id_permintaan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nomor_permintaan VARCHAR(50) NOT NULL UNIQUE,
            tanggal_permintaan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            id_pemohon BIGINT REFERENCES users(id_user),
            unit VARCHAR(100) NOT NULL DEFAULT 'APOTEK',
            status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','DIAJUKAN','DISETUJUI','DIPROSES','SELESAI','DITOLAK','DIBATALKAN')),
            catatan TEXT,
            disetujui_oleh BIGINT REFERENCES users(id_user),
            tanggal_persetujuan TIMESTAMP,
            catatan_persetujuan TEXT,
            dibuat_oleh BIGINT REFERENCES users(id_user),
            diubah_oleh BIGINT REFERENCES users(id_user),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )");
        $this->db->query("CREATE TABLE IF NOT EXISTS permintaan_pengadaan_detail (
            id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_permintaan BIGINT NOT NULL REFERENCES permintaan_pengadaan(id_permintaan) ON DELETE CASCADE,
            id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
            satuan VARCHAR(50),
            harga_referensi NUMERIC(15,2) NOT NULL DEFAULT 0,
            stok_saat_minta INTEGER NOT NULL DEFAULT 0,
            jumlah_minta INTEGER NOT NULL CHECK (jumlah_minta > 0),
            catatan TEXT,
            UNIQUE (id_permintaan, id_obat)
        )");
        $this->db->query("CREATE TABLE IF NOT EXISTS permintaan_status_log (
            id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_permintaan BIGINT NOT NULL REFERENCES permintaan_pengadaan(id_permintaan) ON DELETE CASCADE,
            status_lama VARCHAR(20),
            status_baru VARCHAR(20) NOT NULL,
            id_user BIGINT REFERENCES users(id_user),
            tanggal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            catatan TEXT
        )");
        $this->db->query('CREATE INDEX IF NOT EXISTS idx_permintaan_status ON permintaan_pengadaan (status)');

        // 3. PO boleh merujuk permintaan yang disetujui.
        $this->db->query('ALTER TABLE pengadaan_obat ADD COLUMN IF NOT EXISTS id_permintaan BIGINT REFERENCES permintaan_pengadaan(id_permintaan)');

        // 4. Penerimaan: dokumen + penerima + workflow konfirmasi (data lama = DIKONFIRMASI).
        $this->db->query("ALTER TABLE penerimaan_obat
            ADD COLUMN IF NOT EXISTS no_surat_jalan character varying(100),
            ADD COLUMN IF NOT EXISTS no_faktur character varying(100),
            ADD COLUMN IF NOT EXISTS id_penerima BIGINT REFERENCES users(id_user),
            ADD COLUMN IF NOT EXISTS catatan TEXT,
            ADD COLUMN IF NOT EXISTS status_konfirmasi VARCHAR(20) NOT NULL DEFAULT 'DIKONFIRMASI'
                CHECK (status_konfirmasi IN ('DRAFT','DIPERIKSA','DIKONFIRMASI','DIBATALKAN'))");

        // 5. Retur pembelian: pemutus + batch/ED; normalisasi status lama.
        $this->db->query('ALTER TABLE retur_pengadaan
            ADD COLUMN IF NOT EXISTS diproses_oleh BIGINT REFERENCES users(id_user),
            ADD COLUMN IF NOT EXISTS tanggal_keputusan TIMESTAMP');
        $this->db->query("ALTER TABLE retur_pengadaan_detail
            ADD COLUMN IF NOT EXISTS nomor_batch character varying(100),
            ADD COLUMN IF NOT EXISTS tanggal_kadaluarsa date");
        $this->db->query("UPDATE retur_pengadaan SET status = 'DIAJUKAN' WHERE status = 'Diajukan'");

        // 6. Stok per batch + mutasi diperkaya (NULL = data lama/tanpa batch).
        $this->db->query("CREATE TABLE IF NOT EXISTS stok_batch (
            id_batch BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            id_obat BIGINT NOT NULL REFERENCES obat(id_obat) ON DELETE RESTRICT,
            nomor_batch VARCHAR(100),
            tanggal_kadaluarsa DATE,
            jumlah INTEGER NOT NULL DEFAULT 0 CHECK (jumlah >= 0),
            dibuat_oleh BIGINT REFERENCES users(id_user),
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        )");
        $this->db->query('CREATE INDEX IF NOT EXISTS idx_stok_batch_obat ON stok_batch (id_obat)');
        $this->db->query('CREATE INDEX IF NOT EXISTS idx_stok_batch_ed ON stok_batch (tanggal_kadaluarsa)');
        $this->db->query('ALTER TABLE mutasi_stok
            ADD COLUMN IF NOT EXISTS id_batch BIGINT REFERENCES stok_batch(id_batch),
            ADD COLUMN IF NOT EXISTS saldo INTEGER,
            ADD COLUMN IF NOT EXISTS id_user BIGINT REFERENCES users(id_user)');

        // 7. Permission persediaan -> role yang sudah pegang kelola_pengadaan.
        $perms = array(
            array('kelola_permintaan', 'PERSEDIAAN'),
            array('setujui_permintaan', 'PERSEDIAAN'),
            array('kelola_penerimaan', 'PERSEDIAAN'),
            array('konfirmasi_penerimaan', 'PERSEDIAAN'),
            array('kelola_retur_pembelian', 'PERSEDIAAN'),
        );
        foreach ($perms as $pm) {
            $this->db->query("INSERT INTO permissions (nama_permission, modul) VALUES (?, ?)
                ON CONFLICT (nama_permission) DO NOTHING", $pm);
        }
        $this->db->query("INSERT INTO role_permissions (id_role, id_permission)
            SELECT DISTINCT r.id_role, p.id_permission FROM roles r
            JOIN role_permissions rp ON rp.id_role = r.id_role
            JOIN permissions kelola ON kelola.id_permission = rp.id_permission AND kelola.nama_permission = 'kelola_pengadaan'
            JOIN permissions p ON p.nama_permission IN
                ('kelola_permintaan','setujui_permintaan','kelola_penerimaan','konfirmasi_penerimaan','kelola_retur_pembelian')
            WHERE NOT EXISTS (SELECT 1 FROM role_permissions x
                WHERE x.id_role = r.id_role AND x.id_permission = p.id_permission)");
    }

    public function down()
    {
        // FK PO->permintaan dicabut dulu sebelum tabel permintaan di-drop.
        $this->db->query('ALTER TABLE pengadaan_obat DROP COLUMN IF EXISTS id_permintaan');
        $this->db->query('ALTER TABLE mutasi_stok DROP COLUMN IF EXISTS id_user');
        $this->db->query('ALTER TABLE mutasi_stok DROP COLUMN IF EXISTS saldo');
        $this->db->query('ALTER TABLE mutasi_stok DROP COLUMN IF EXISTS id_batch');
        $this->db->query('DROP TABLE IF EXISTS stok_batch');
        $this->db->query("UPDATE retur_pengadaan SET status = 'Diajukan' WHERE status = 'DIAJUKAN'");
        $this->db->query('ALTER TABLE retur_pengadaan_detail DROP COLUMN IF EXISTS tanggal_kadaluarsa');
        $this->db->query('ALTER TABLE retur_pengadaan_detail DROP COLUMN IF EXISTS nomor_batch');
        $this->db->query('ALTER TABLE retur_pengadaan DROP COLUMN IF EXISTS tanggal_keputusan');
        $this->db->query('ALTER TABLE retur_pengadaan DROP COLUMN IF EXISTS diproses_oleh');
        $this->db->query('ALTER TABLE penerimaan_obat DROP COLUMN IF EXISTS status_konfirmasi');
        $this->db->query('ALTER TABLE penerimaan_obat DROP COLUMN IF EXISTS catatan');
        $this->db->query('ALTER TABLE penerimaan_obat DROP COLUMN IF EXISTS id_penerima');
        $this->db->query('ALTER TABLE penerimaan_obat DROP COLUMN IF EXISTS no_faktur');
        $this->db->query('ALTER TABLE penerimaan_obat DROP COLUMN IF EXISTS no_surat_jalan');
        $this->db->query('DROP TABLE IF EXISTS permintaan_status_log');
        $this->db->query('DROP TABLE IF EXISTS permintaan_pengadaan_detail');
        $this->db->query('DROP TABLE IF EXISTS permintaan_pengadaan');
        $this->db->query('ALTER TABLE obat DROP COLUMN IF EXISTS harga_jual');
        $this->db->query('ALTER TABLE obat DROP COLUMN IF EXISTS harga_satuan');
        $this->db->query('ALTER TABLE obat DROP COLUMN IF EXISTS id_supplier_utama');
        $this->db->query('ALTER TABLE obat DROP COLUMN IF EXISTS produsen');
        $this->db->query('ALTER TABLE obat DROP COLUMN IF EXISTS kandungan');
        $this->db->query('ALTER TABLE obat DROP COLUMN IF EXISTS bentuk_sediaan');
        $this->db->query('ALTER TABLE obat DROP COLUMN IF EXISTS kategori');
    }
}
