<?php defined('BASEPATH') || exit('No direct script access allowed');

class Migration_master_satuan extends Migration
{
    public function up()
    {
        // 1. Buat tabel master_satuan
        $this->db->query("CREATE TABLE IF NOT EXISTS master_satuan (
            id_satuan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            nama_satuan character varying(100) NOT NULL UNIQUE,
            status character varying(20) DEFAULT 'AKTIF' NOT NULL,
            created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
            CONSTRAINT chk_satuan_status CHECK (status IN ('AKTIF', 'NONAKTIF'))
        )");

        // 2. Insert data unik dari kolom satuan tabel obat ke master_satuan
        $this->db->query("INSERT INTO master_satuan (nama_satuan)
            SELECT DISTINCT satuan FROM obat WHERE satuan IS NOT NULL AND satuan != ''
            ON CONFLICT (nama_satuan) DO NOTHING");

        // 3. Tambahkan kolom id_satuan di tabel obat
        $this->db->query("ALTER TABLE obat
            ADD COLUMN IF NOT EXISTS id_satuan BIGINT");

        // 4. Update tabel obat dengan id_satuan
        $this->db->query("UPDATE obat o
            SET id_satuan = ms.id_satuan
            FROM master_satuan ms
            WHERE o.satuan = ms.nama_satuan");

        // 5. Tambahkan Foreign Key
        $this->db->query("ALTER TABLE obat
            ADD CONSTRAINT fk_obat_satuan FOREIGN KEY (id_satuan) REFERENCES master_satuan(id_satuan) ON DELETE RESTRICT");
    }

    public function down()
    {
        // 1. Hapus Foreign Key dan kolom id_satuan
        $this->db->query("ALTER TABLE obat DROP CONSTRAINT IF EXISTS fk_obat_satuan");
        $this->db->query("ALTER TABLE obat DROP COLUMN IF EXISTS id_satuan");

        // 2. Hapus tabel master_satuan
        $this->db->query("DROP TABLE IF EXISTS master_satuan");
    }
}
