-- =====================================================================
-- Database Apotek - struktur terbaru + seed minimal (versi repository)
-- CATATAN: database/apotek_latest.sql HANYA untuk database KOSONG.
-- Database LAMA yang sudah berisi data: gunakan
-- database/update_dari_versi_lama.sql (idempoten).
-- Cara pakai (kosong):
--   1. CREATE DATABASE apotek;
--   2. psql -U postgres -d apotek -f database/apotek_latest.sql
-- Isi Bagian B SEED: roles, permissions, role_permissions, users,
-- user_roles, dokter, spesialis, pelayanan, poli, ruangan, obat,
-- stok_obat, supplier, pasien-portal (dummy, TANPA transaksi).
-- Akun testing (password: admin123 - hash bawaan aplikasi):
--   admin / pelayanan / dokter / apoteker / pasien
-- Perubahan: tabel pengadaan [001], dokter.id_user [002],
-- pasien.id_user [003], pesanan_online(+detail) + jenis ONLINE [004],
-- permission View per-context + apotek online.
-- =====================================================================

--
-- PostgreSQL database dump
--

\restrict ybrW0HOQop4Yd9cKtIHKaeP0jflV32COkwkokwFyNmsX5kcMHiNoYqa7pgVftfB

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: antrian; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.antrian (
    id_antrian bigint NOT NULL,
    id_kunjungan bigint NOT NULL,
    nomor_antrian character varying(30) NOT NULL,
    tanggal_antrian date DEFAULT CURRENT_DATE NOT NULL,
    status character varying(30) DEFAULT 'MENUNGGU'::character varying NOT NULL,
    waktu_dipanggil timestamp without time zone,
    waktu_mulai timestamp without time zone,
    waktu_selesai timestamp without time zone,
    CONSTRAINT chk_antrian_status CHECK (((status)::text = ANY ((ARRAY['MENUNGGU'::character varying, 'DIPANGGIL'::character varying, 'SEDANG_DIPERIKSA'::character varying, 'SELESAI'::character varying, 'DILEWATI'::character varying, 'BATAL'::character varying])::text[])))
);


--
-- Name: antrian_id_antrian_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.antrian ALTER COLUMN id_antrian ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.antrian_id_antrian_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id_log bigint NOT NULL,
    id_user bigint,
    aksi character varying(50) NOT NULL,
    modul character varying(100),
    id_data bigint,
    waktu timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    keterangan text
);


--
-- Name: audit_logs_id_log_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id_log ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_log_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: diagnosis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.diagnosis (
    id_diagnosis bigint NOT NULL,
    id_pemeriksaan bigint NOT NULL,
    nama_diagnosis character varying(255) NOT NULL,
    keterangan text
);


--
-- Name: diagnosis_id_diagnosis_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.diagnosis ALTER COLUMN id_diagnosis ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.diagnosis_id_diagnosis_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: dokter; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.dokter (
    id_dokter bigint NOT NULL,
    id_spesialis bigint,
    nama_dokter character varying(150) NOT NULL,
    no_sip character varying(50),
    no_hp character varying(30),
    tarif numeric(15,2) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_user bigint,
    CONSTRAINT chk_dokter_status CHECK (((status)::text = ANY ((ARRAY['AKTIF'::character varying, 'NONAKTIF'::character varying])::text[]))),
    CONSTRAINT chk_dokter_tarif CHECK ((tarif >= (0)::numeric))
);


--
-- Name: dokter_id_dokter_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.dokter ALTER COLUMN id_dokter ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dokter_id_dokter_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: kunjungan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kunjungan (
    id_kunjungan bigint NOT NULL,
    id_pasien bigint NOT NULL,
    id_pelayanan bigint NOT NULL,
    id_poli bigint NOT NULL,
    id_dokter bigint NOT NULL,
    id_ruangan bigint NOT NULL,
    tanggal_kunjungan timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(30) DEFAULT 'TERDAFTAR'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_kunjungan_status CHECK (((status)::text = ANY ((ARRAY['TERDAFTAR'::character varying, 'MENUNGGU'::character varying, 'DIPROSES'::character varying, 'SELESAI'::character varying, 'BATAL'::character varying])::text[])))
);


--
-- Name: kunjungan_id_kunjungan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.kunjungan ALTER COLUMN id_kunjungan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kunjungan_id_kunjungan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mutasi_stok; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mutasi_stok (
    id_mutasi bigint NOT NULL,
    id_obat bigint NOT NULL,
    jenis_mutasi character varying(10) NOT NULL,
    jumlah integer NOT NULL,
    tanggal timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    sumber character varying(100),
    id_referensi bigint,
    keterangan text,
    CONSTRAINT chk_mutasi_jenis CHECK (((jenis_mutasi)::text = ANY ((ARRAY['MASUK'::character varying, 'KELUAR'::character varying])::text[]))),
    CONSTRAINT chk_mutasi_jumlah CHECK ((jumlah > 0))
);


--
-- Name: mutasi_stok_id_mutasi_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mutasi_stok ALTER COLUMN id_mutasi ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mutasi_stok_id_mutasi_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: obat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.obat (
    id_obat bigint NOT NULL,
    kode_obat character varying(50) NOT NULL,
    nama_obat character varying(150) NOT NULL,
    jenis_obat character varying(100),
    satuan character varying(50) NOT NULL,
    harga numeric(15,2) DEFAULT 0 NOT NULL,
    stok_minimum integer DEFAULT 0 NOT NULL,
    wajib_resep boolean DEFAULT false NOT NULL,
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_obat_harga CHECK ((harga >= (0)::numeric)),
    CONSTRAINT chk_obat_status CHECK (((status)::text = ANY ((ARRAY['AKTIF'::character varying, 'NONAKTIF'::character varying])::text[]))),
    CONSTRAINT chk_obat_stok_minimum CHECK ((stok_minimum >= 0))
);


--
-- Name: obat_id_obat_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.obat ALTER COLUMN id_obat ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.obat_id_obat_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pasien; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pasien (
    id_pasien bigint NOT NULL,
    no_rm character varying(30) NOT NULL,
    nik character varying(30),
    nama character varying(150) NOT NULL,
    tanggal_lahir date,
    jenis_kelamin character varying(1),
    alamat text,
    no_hp character varying(30),
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    id_user bigint,
    CONSTRAINT chk_pasien_jenis_kelamin CHECK (((jenis_kelamin IS NULL) OR ((jenis_kelamin)::text = ANY ((ARRAY['L'::character varying, 'P'::character varying])::text[])))),
    CONSTRAINT chk_pasien_status CHECK (((status)::text = ANY ((ARRAY['AKTIF'::character varying, 'NONAKTIF'::character varying])::text[])))
);


--
-- Name: pasien_id_pasien_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pasien ALTER COLUMN id_pasien ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pasien_id_pasien_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pelayanan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pelayanan (
    id_pelayanan bigint NOT NULL,
    nama_pelayanan character varying(150) NOT NULL,
    jenis_pelayanan character varying(100),
    tarif numeric(15,2) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    CONSTRAINT chk_pelayanan_status CHECK (((status)::text = ANY ((ARRAY['AKTIF'::character varying, 'NONAKTIF'::character varying])::text[]))),
    CONSTRAINT chk_pelayanan_tarif CHECK ((tarif >= (0)::numeric))
);


--
-- Name: pelayanan_id_pelayanan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pelayanan ALTER COLUMN id_pelayanan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pelayanan_id_pelayanan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pembayaran; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pembayaran (
    id_pembayaran bigint NOT NULL,
    id_transaksi bigint NOT NULL,
    tanggal_pembayaran timestamp without time zone,
    jumlah_bayar numeric(15,2) DEFAULT 0 NOT NULL,
    kembalian numeric(15,2) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'BELUM_DIBAYAR'::character varying NOT NULL,
    CONSTRAINT chk_pembayaran_jumlah CHECK ((jumlah_bayar >= (0)::numeric)),
    CONSTRAINT chk_pembayaran_kembalian CHECK ((kembalian >= (0)::numeric)),
    CONSTRAINT chk_pembayaran_status CHECK (((status)::text = ANY ((ARRAY['BELUM_DIBAYAR'::character varying, 'LUNAS'::character varying, 'BATAL'::character varying])::text[])))
);


--
-- Name: pembayaran_id_pembayaran_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pembayaran ALTER COLUMN id_pembayaran ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pembayaran_id_pembayaran_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pemeriksaan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pemeriksaan (
    id_pemeriksaan bigint NOT NULL,
    id_kunjungan bigint NOT NULL,
    id_dokter bigint NOT NULL,
    keluhan text,
    hasil_pemeriksaan text,
    catatan_dokter text,
    tanggal_pemeriksaan timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(20) DEFAULT 'DIPROSES'::character varying NOT NULL,
    CONSTRAINT chk_pemeriksaan_status CHECK (((status)::text = ANY ((ARRAY['DIPROSES'::character varying, 'SELESAI'::character varying])::text[])))
);


--
-- Name: pemeriksaan_id_pemeriksaan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pemeriksaan ALTER COLUMN id_pemeriksaan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pemeriksaan_id_pemeriksaan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: penerimaan_obat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.penerimaan_obat (
    id_penerimaan bigint NOT NULL,
    id_pengadaan bigint NOT NULL,
    nomor_penerimaan character varying(50) NOT NULL,
    tanggal_terima timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(30) DEFAULT 'Sesuai'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: penerimaan_obat_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.penerimaan_obat_detail (
    id_detail bigint NOT NULL,
    id_penerimaan bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah_terima integer NOT NULL,
    kondisi character varying(30) DEFAULT 'Baik'::character varying NOT NULL
);


--
-- Name: penerimaan_obat_detail_id_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.penerimaan_obat_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penerimaan_obat_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: penerimaan_obat_id_penerimaan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.penerimaan_obat ALTER COLUMN id_penerimaan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penerimaan_obat_id_penerimaan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pengadaan_obat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pengadaan_obat (
    id_pengadaan bigint NOT NULL,
    nomor_pengadaan character varying(50) NOT NULL,
    id_supplier bigint NOT NULL,
    tanggal_pesanan timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total numeric DEFAULT 0 NOT NULL,
    status character varying(30) DEFAULT 'Dipesan'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: pengadaan_obat_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pengadaan_obat_detail (
    id_detail bigint NOT NULL,
    id_pengadaan bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah_pesan integer NOT NULL,
    harga numeric NOT NULL,
    subtotal numeric NOT NULL
);


--
-- Name: pengadaan_obat_detail_id_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pengadaan_obat_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pengadaan_obat_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pengadaan_obat_id_pengadaan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pengadaan_obat ALTER COLUMN id_pengadaan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pengadaan_obat_id_pengadaan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: penjualan_obat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.penjualan_obat (
    id_penjualan bigint NOT NULL,
    id_resep bigint,
    id_pasien bigint,
    nomor_penjualan character varying(50) NOT NULL,
    tanggal_penjualan timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    jenis_penjualan character varying(20) NOT NULL,
    total numeric(15,2) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'DRAFT'::character varying NOT NULL,
    CONSTRAINT chk_jenis_penjualan CHECK (((jenis_penjualan)::text = ANY ((ARRAY['RESEP'::character varying, 'LANGSUNG'::character varying, 'ONLINE'::character varying])::text[]))),
    CONSTRAINT chk_penjualan_resep_relation CHECK (((((jenis_penjualan)::text = 'RESEP'::text) AND (id_resep IS NOT NULL)) OR ((jenis_penjualan)::text = ANY ((ARRAY['LANGSUNG'::character varying, 'ONLINE'::character varying])::text[])))),
    CONSTRAINT chk_penjualan_status CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'DIPROSES'::character varying, 'SELESAI'::character varying, 'BATAL'::character varying])::text[]))),
    CONSTRAINT chk_penjualan_total CHECK ((total >= (0)::numeric))
);


--
-- Name: penjualan_obat_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.penjualan_obat_detail (
    id_detail bigint NOT NULL,
    id_penjualan bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah integer NOT NULL,
    harga numeric(15,2) DEFAULT 0 NOT NULL,
    subtotal numeric(15,2) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_penjualan_detail_harga CHECK ((harga >= (0)::numeric)),
    CONSTRAINT chk_penjualan_detail_jumlah CHECK ((jumlah > 0)),
    CONSTRAINT chk_penjualan_detail_subtotal CHECK ((subtotal >= (0)::numeric))
);


--
-- Name: penjualan_obat_detail_id_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.penjualan_obat_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penjualan_obat_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: penjualan_obat_id_penjualan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.penjualan_obat ALTER COLUMN id_penjualan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penjualan_obat_id_penjualan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions (
    id_permission bigint NOT NULL,
    nama_permission character varying(100) NOT NULL,
    modul character varying(100)
);


--
-- Name: permissions_id_permission_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.permissions ALTER COLUMN id_permission ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.permissions_id_permission_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pesanan_online; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pesanan_online (
    id_pesanan bigint NOT NULL,
    id_pasien bigint NOT NULL,
    id_penjualan bigint,
    id_tagihan bigint,
    nomor_pesanan character varying(50) NOT NULL,
    tanggal_pesanan timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    alamat_kirim text NOT NULL,
    total numeric(15,2) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'MENUNGGU'::character varying NOT NULL,
    status_bayar character varying(20) DEFAULT 'BELUM_DIBAYAR'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_pesanan_bayar CHECK (((status_bayar)::text = ANY ((ARRAY['BELUM_DIBAYAR'::character varying, 'LUNAS'::character varying, 'BATAL'::character varying])::text[]))),
    CONSTRAINT chk_pesanan_status CHECK (((status)::text = ANY ((ARRAY['MENUNGGU'::character varying, 'DIVERIFIKASI'::character varying, 'DIPROSES'::character varying, 'SIAP'::character varying, 'SELESAI'::character varying, 'BATAL'::character varying])::text[]))),
    CONSTRAINT chk_pesanan_total CHECK ((total >= (0)::numeric))
);


--
-- Name: pesanan_online_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pesanan_online_detail (
    id_detail bigint NOT NULL,
    id_pesanan bigint NOT NULL,
    id_obat bigint NOT NULL,
    id_resep bigint,
    jumlah integer NOT NULL,
    harga numeric(15,2) NOT NULL,
    subtotal numeric(15,2) NOT NULL,
    CONSTRAINT chk_pesanan_detail_harga CHECK ((harga >= (0)::numeric)),
    CONSTRAINT chk_pesanan_detail_jumlah CHECK ((jumlah > 0)),
    CONSTRAINT chk_pesanan_detail_subtotal CHECK ((subtotal >= (0)::numeric))
);


--
-- Name: pesanan_online_detail_id_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pesanan_online_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pesanan_online_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pesanan_online_id_pesanan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pesanan_online ALTER COLUMN id_pesanan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pesanan_online_id_pesanan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: poli; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.poli (
    id_poli bigint NOT NULL,
    nama_poli character varying(100) NOT NULL,
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    CONSTRAINT chk_poli_status CHECK (((status)::text = ANY ((ARRAY['AKTIF'::character varying, 'NONAKTIF'::character varying])::text[])))
);


--
-- Name: poli_id_poli_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.poli ALTER COLUMN id_poli ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.poli_id_poli_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resep; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resep (
    id_resep bigint NOT NULL,
    id_pemeriksaan bigint NOT NULL,
    id_pasien bigint NOT NULL,
    id_dokter bigint NOT NULL,
    nomor_resep character varying(50) NOT NULL,
    tanggal_resep timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(30) DEFAULT 'DIBUAT'::character varying NOT NULL,
    catatan text,
    CONSTRAINT chk_resep_status CHECK (((status)::text = ANY ((ARRAY['DIBUAT'::character varying, 'DIPROSES'::character varying, 'SIAP'::character varying, 'DISERAHKAN'::character varying, 'BATAL'::character varying])::text[])))
);


--
-- Name: resep_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.resep_detail (
    id_resep_detail bigint NOT NULL,
    id_resep bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah integer NOT NULL,
    dosis character varying(100),
    aturan_pakai character varying(255),
    keterangan text,
    CONSTRAINT chk_resep_detail_jumlah CHECK ((jumlah > 0))
);


--
-- Name: resep_detail_id_resep_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resep_detail ALTER COLUMN id_resep_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resep_detail_id_resep_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: resep_id_resep_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.resep ALTER COLUMN id_resep ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resep_id_resep_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retur_pengadaan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.retur_pengadaan (
    id_retur bigint NOT NULL,
    id_penerimaan bigint NOT NULL,
    nomor_retur character varying(50) NOT NULL,
    tanggal_retur timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(30) DEFAULT 'Diajukan'::character varying NOT NULL,
    keterangan text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: retur_pengadaan_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.retur_pengadaan_detail (
    id_detail bigint NOT NULL,
    id_retur bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah integer NOT NULL,
    alasan text
);


--
-- Name: retur_pengadaan_detail_id_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.retur_pengadaan_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retur_pengadaan_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retur_pengadaan_id_retur_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.retur_pengadaan ALTER COLUMN id_retur ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retur_pengadaan_id_retur_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    id_role bigint NOT NULL,
    id_permission bigint NOT NULL
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.roles (
    id_role bigint NOT NULL,
    nama_role character varying(100) NOT NULL
);


--
-- Name: roles_id_role_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.roles ALTER COLUMN id_role ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_role_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ruangan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ruangan (
    id_ruangan bigint NOT NULL,
    id_poli bigint,
    nama_ruangan character varying(100) NOT NULL,
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    CONSTRAINT chk_ruangan_status CHECK (((status)::text = ANY ((ARRAY['AKTIF'::character varying, 'NONAKTIF'::character varying])::text[])))
);


--
-- Name: ruangan_id_ruangan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ruangan ALTER COLUMN id_ruangan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ruangan_id_ruangan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spesialis; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.spesialis (
    id_spesialis bigint NOT NULL,
    nama_spesialis character varying(100) NOT NULL,
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    CONSTRAINT chk_spesialis_status CHECK (((status)::text = ANY ((ARRAY['AKTIF'::character varying, 'NONAKTIF'::character varying])::text[])))
);


--
-- Name: spesialis_id_spesialis_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.spesialis ALTER COLUMN id_spesialis ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spesialis_id_spesialis_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: stok_obat; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.stok_obat (
    id_stok bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah_stok integer DEFAULT 0 NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_stok_jumlah CHECK ((jumlah_stok >= 0))
);


--
-- Name: stok_obat_id_stok_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.stok_obat ALTER COLUMN id_stok ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stok_obat_id_stok_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: supplier; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.supplier (
    id_supplier bigint NOT NULL,
    kode_supplier character varying(50) NOT NULL,
    nama_supplier character varying(150) NOT NULL,
    alamat text,
    no_hp character varying(20),
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: supplier_id_supplier_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.supplier ALTER COLUMN id_supplier ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_id_supplier_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tagihan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tagihan (
    id_tagihan bigint NOT NULL,
    id_kunjungan bigint,
    nomor_tagihan character varying(50) NOT NULL,
    tanggal_tagihan timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total numeric(15,2) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'BELUM_DIBAYAR'::character varying NOT NULL,
    CONSTRAINT chk_tagihan_status CHECK (((status)::text = ANY ((ARRAY['BELUM_DIBAYAR'::character varying, 'LUNAS'::character varying, 'BATAL'::character varying])::text[]))),
    CONSTRAINT chk_tagihan_total CHECK ((total >= (0)::numeric))
);


--
-- Name: tagihan_detail; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tagihan_detail (
    id_detail bigint NOT NULL,
    id_tagihan bigint NOT NULL,
    jenis_item character varying(20) NOT NULL,
    id_referensi bigint,
    nama_item character varying(255) NOT NULL,
    jumlah integer DEFAULT 1 NOT NULL,
    harga numeric(15,2) DEFAULT 0 NOT NULL,
    subtotal numeric(15,2) DEFAULT 0 NOT NULL,
    CONSTRAINT chk_tagihan_detail_harga CHECK ((harga >= (0)::numeric)),
    CONSTRAINT chk_tagihan_detail_jenis CHECK (((jenis_item)::text = ANY ((ARRAY['PELAYANAN'::character varying, 'TINDAKAN'::character varying, 'OBAT'::character varying])::text[]))),
    CONSTRAINT chk_tagihan_detail_jumlah CHECK ((jumlah > 0)),
    CONSTRAINT chk_tagihan_detail_subtotal CHECK ((subtotal >= (0)::numeric))
);


--
-- Name: tagihan_detail_id_detail_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tagihan_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tagihan_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tagihan_id_tagihan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tagihan ALTER COLUMN id_tagihan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tagihan_id_tagihan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tindakan; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tindakan (
    id_tindakan bigint NOT NULL,
    id_pemeriksaan bigint NOT NULL,
    nama_tindakan character varying(255) NOT NULL,
    biaya numeric(15,2) DEFAULT 0 NOT NULL,
    keterangan text,
    CONSTRAINT chk_tindakan_biaya CHECK ((biaya >= (0)::numeric))
);


--
-- Name: tindakan_id_tindakan_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tindakan ALTER COLUMN id_tindakan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tindakan_id_tindakan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaksi; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.transaksi (
    id_transaksi bigint NOT NULL,
    id_tagihan bigint NOT NULL,
    nomor_transaksi character varying(50) NOT NULL,
    tanggal_transaksi timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total numeric(15,2) DEFAULT 0 NOT NULL,
    status character varying(20) DEFAULT 'BELUM_DIBAYAR'::character varying NOT NULL,
    CONSTRAINT chk_transaksi_status CHECK (((status)::text = ANY ((ARRAY['BELUM_DIBAYAR'::character varying, 'LUNAS'::character varying, 'BATAL'::character varying])::text[]))),
    CONSTRAINT chk_transaksi_total CHECK ((total >= (0)::numeric))
);


--
-- Name: transaksi_id_transaksi_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.transaksi ALTER COLUMN id_transaksi ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaksi_id_transaksi_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_roles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_roles (
    id_user bigint NOT NULL,
    id_role bigint NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id_user bigint NOT NULL,
    username character varying(100) NOT NULL,
    password character varying(255) NOT NULL,
    nama character varying(150) NOT NULL,
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT chk_users_status CHECK (((status)::text = ANY ((ARRAY['AKTIF'::character varying, 'NONAKTIF'::character varying])::text[])))
);


--
-- Name: users_id_user_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: antrian antrian_id_kunjungan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.antrian
    ADD CONSTRAINT antrian_id_kunjungan_key UNIQUE (id_kunjungan);


--
-- Name: antrian antrian_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.antrian
    ADD CONSTRAINT antrian_pkey PRIMARY KEY (id_antrian);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id_log);


--
-- Name: diagnosis diagnosis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagnosis
    ADD CONSTRAINT diagnosis_pkey PRIMARY KEY (id_diagnosis);


--
-- Name: dokter dokter_no_sip_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dokter
    ADD CONSTRAINT dokter_no_sip_key UNIQUE (no_sip);


--
-- Name: dokter dokter_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dokter
    ADD CONSTRAINT dokter_pkey PRIMARY KEY (id_dokter);


--
-- Name: kunjungan kunjungan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kunjungan
    ADD CONSTRAINT kunjungan_pkey PRIMARY KEY (id_kunjungan);


--
-- Name: mutasi_stok mutasi_stok_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mutasi_stok
    ADD CONSTRAINT mutasi_stok_pkey PRIMARY KEY (id_mutasi);


--
-- Name: obat obat_kode_obat_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obat
    ADD CONSTRAINT obat_kode_obat_key UNIQUE (kode_obat);


--
-- Name: obat obat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.obat
    ADD CONSTRAINT obat_pkey PRIMARY KEY (id_obat);


--
-- Name: pasien pasien_nik_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pasien
    ADD CONSTRAINT pasien_nik_key UNIQUE (nik);


--
-- Name: pasien pasien_no_rm_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pasien
    ADD CONSTRAINT pasien_no_rm_key UNIQUE (no_rm);


--
-- Name: pasien pasien_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pasien
    ADD CONSTRAINT pasien_pkey PRIMARY KEY (id_pasien);


--
-- Name: pelayanan pelayanan_nama_pelayanan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pelayanan
    ADD CONSTRAINT pelayanan_nama_pelayanan_key UNIQUE (nama_pelayanan);


--
-- Name: pelayanan pelayanan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pelayanan
    ADD CONSTRAINT pelayanan_pkey PRIMARY KEY (id_pelayanan);


--
-- Name: pembayaran pembayaran_id_transaksi_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pembayaran
    ADD CONSTRAINT pembayaran_id_transaksi_key UNIQUE (id_transaksi);


--
-- Name: pembayaran pembayaran_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pembayaran
    ADD CONSTRAINT pembayaran_pkey PRIMARY KEY (id_pembayaran);


--
-- Name: pemeriksaan pemeriksaan_id_kunjungan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pemeriksaan
    ADD CONSTRAINT pemeriksaan_id_kunjungan_key UNIQUE (id_kunjungan);


--
-- Name: pemeriksaan pemeriksaan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pemeriksaan
    ADD CONSTRAINT pemeriksaan_pkey PRIMARY KEY (id_pemeriksaan);


--
-- Name: penerimaan_obat_detail penerimaan_obat_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penerimaan_obat_detail
    ADD CONSTRAINT penerimaan_obat_detail_pkey PRIMARY KEY (id_detail);


--
-- Name: penerimaan_obat penerimaan_obat_nomor_penerimaan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penerimaan_obat
    ADD CONSTRAINT penerimaan_obat_nomor_penerimaan_key UNIQUE (nomor_penerimaan);


--
-- Name: penerimaan_obat penerimaan_obat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penerimaan_obat
    ADD CONSTRAINT penerimaan_obat_pkey PRIMARY KEY (id_penerimaan);


--
-- Name: pengadaan_obat_detail pengadaan_obat_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengadaan_obat_detail
    ADD CONSTRAINT pengadaan_obat_detail_pkey PRIMARY KEY (id_detail);


--
-- Name: pengadaan_obat pengadaan_obat_nomor_pengadaan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengadaan_obat
    ADD CONSTRAINT pengadaan_obat_nomor_pengadaan_key UNIQUE (nomor_pengadaan);


--
-- Name: pengadaan_obat pengadaan_obat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengadaan_obat
    ADD CONSTRAINT pengadaan_obat_pkey PRIMARY KEY (id_pengadaan);


--
-- Name: penjualan_obat_detail penjualan_obat_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penjualan_obat_detail
    ADD CONSTRAINT penjualan_obat_detail_pkey PRIMARY KEY (id_detail);


--
-- Name: penjualan_obat penjualan_obat_nomor_penjualan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penjualan_obat
    ADD CONSTRAINT penjualan_obat_nomor_penjualan_key UNIQUE (nomor_penjualan);


--
-- Name: penjualan_obat penjualan_obat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penjualan_obat
    ADD CONSTRAINT penjualan_obat_pkey PRIMARY KEY (id_penjualan);


--
-- Name: permissions permissions_nama_permission_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_nama_permission_key UNIQUE (nama_permission);


--
-- Name: permissions permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions
    ADD CONSTRAINT permissions_pkey PRIMARY KEY (id_permission);


--
-- Name: pesanan_online_detail pesanan_online_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online_detail
    ADD CONSTRAINT pesanan_online_detail_pkey PRIMARY KEY (id_detail);


--
-- Name: pesanan_online pesanan_online_nomor_pesanan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online
    ADD CONSTRAINT pesanan_online_nomor_pesanan_key UNIQUE (nomor_pesanan);


--
-- Name: pesanan_online pesanan_online_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online
    ADD CONSTRAINT pesanan_online_pkey PRIMARY KEY (id_pesanan);


--
-- Name: poli poli_nama_poli_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.poli
    ADD CONSTRAINT poli_nama_poli_key UNIQUE (nama_poli);


--
-- Name: poli poli_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.poli
    ADD CONSTRAINT poli_pkey PRIMARY KEY (id_poli);


--
-- Name: resep_detail resep_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep_detail
    ADD CONSTRAINT resep_detail_pkey PRIMARY KEY (id_resep_detail);


--
-- Name: resep resep_id_pemeriksaan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep
    ADD CONSTRAINT resep_id_pemeriksaan_key UNIQUE (id_pemeriksaan);


--
-- Name: resep resep_nomor_resep_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep
    ADD CONSTRAINT resep_nomor_resep_key UNIQUE (nomor_resep);


--
-- Name: resep resep_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep
    ADD CONSTRAINT resep_pkey PRIMARY KEY (id_resep);


--
-- Name: retur_pengadaan_detail retur_pengadaan_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retur_pengadaan_detail
    ADD CONSTRAINT retur_pengadaan_detail_pkey PRIMARY KEY (id_detail);


--
-- Name: retur_pengadaan retur_pengadaan_nomor_retur_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retur_pengadaan
    ADD CONSTRAINT retur_pengadaan_nomor_retur_key UNIQUE (nomor_retur);


--
-- Name: retur_pengadaan retur_pengadaan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retur_pengadaan
    ADD CONSTRAINT retur_pengadaan_pkey PRIMARY KEY (id_retur);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id_role, id_permission);


--
-- Name: roles roles_nama_role_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_nama_role_key UNIQUE (nama_role);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id_role);


--
-- Name: ruangan ruangan_nama_ruangan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ruangan
    ADD CONSTRAINT ruangan_nama_ruangan_key UNIQUE (nama_ruangan);


--
-- Name: ruangan ruangan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ruangan
    ADD CONSTRAINT ruangan_pkey PRIMARY KEY (id_ruangan);


--
-- Name: spesialis spesialis_nama_spesialis_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spesialis
    ADD CONSTRAINT spesialis_nama_spesialis_key UNIQUE (nama_spesialis);


--
-- Name: spesialis spesialis_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spesialis
    ADD CONSTRAINT spesialis_pkey PRIMARY KEY (id_spesialis);


--
-- Name: stok_obat stok_obat_id_obat_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stok_obat
    ADD CONSTRAINT stok_obat_id_obat_key UNIQUE (id_obat);


--
-- Name: stok_obat stok_obat_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stok_obat
    ADD CONSTRAINT stok_obat_pkey PRIMARY KEY (id_stok);


--
-- Name: supplier supplier_kode_supplier_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_kode_supplier_key UNIQUE (kode_supplier);


--
-- Name: supplier supplier_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.supplier
    ADD CONSTRAINT supplier_pkey PRIMARY KEY (id_supplier);


--
-- Name: tagihan_detail tagihan_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tagihan_detail
    ADD CONSTRAINT tagihan_detail_pkey PRIMARY KEY (id_detail);


--
-- Name: tagihan tagihan_nomor_tagihan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tagihan
    ADD CONSTRAINT tagihan_nomor_tagihan_key UNIQUE (nomor_tagihan);


--
-- Name: tagihan tagihan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tagihan
    ADD CONSTRAINT tagihan_pkey PRIMARY KEY (id_tagihan);


--
-- Name: tindakan tindakan_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tindakan
    ADD CONSTRAINT tindakan_pkey PRIMARY KEY (id_tindakan);


--
-- Name: transaksi transaksi_id_tagihan_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaksi
    ADD CONSTRAINT transaksi_id_tagihan_key UNIQUE (id_tagihan);


--
-- Name: transaksi transaksi_nomor_transaksi_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaksi
    ADD CONSTRAINT transaksi_nomor_transaksi_key UNIQUE (nomor_transaksi);


--
-- Name: transaksi transaksi_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaksi
    ADD CONSTRAINT transaksi_pkey PRIMARY KEY (id_transaksi);


--
-- Name: user_roles user_roles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (id_user, id_role);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id_user);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: idx_antrian_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_antrian_status ON public.antrian USING btree (status);


--
-- Name: idx_antrian_tanggal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_antrian_tanggal ON public.antrian USING btree (tanggal_antrian);


--
-- Name: idx_audit_modul; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_modul ON public.audit_logs USING btree (modul);


--
-- Name: idx_audit_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_user ON public.audit_logs USING btree (id_user);


--
-- Name: idx_audit_waktu; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_waktu ON public.audit_logs USING btree (waktu);


--
-- Name: idx_diagnosis_pemeriksaan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_diagnosis_pemeriksaan ON public.diagnosis USING btree (id_pemeriksaan);


--
-- Name: idx_dokter_nama; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dokter_nama ON public.dokter USING btree (nama_dokter);


--
-- Name: idx_dokter_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_dokter_user ON public.dokter USING btree (id_user);


--
-- Name: idx_kunjungan_dokter; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kunjungan_dokter ON public.kunjungan USING btree (id_dokter);


--
-- Name: idx_kunjungan_pasien; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kunjungan_pasien ON public.kunjungan USING btree (id_pasien);


--
-- Name: idx_kunjungan_poli; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kunjungan_poli ON public.kunjungan USING btree (id_poli);


--
-- Name: idx_kunjungan_tanggal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_kunjungan_tanggal ON public.kunjungan USING btree (tanggal_kunjungan);


--
-- Name: idx_mutasi_obat; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mutasi_obat ON public.mutasi_stok USING btree (id_obat);


--
-- Name: idx_mutasi_tanggal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mutasi_tanggal ON public.mutasi_stok USING btree (tanggal);


--
-- Name: idx_obat_nama; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_obat_nama ON public.obat USING btree (nama_obat);


--
-- Name: idx_pasien_nama; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pasien_nama ON public.pasien USING btree (nama);


--
-- Name: idx_pasien_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pasien_user ON public.pasien USING btree (id_user);


--
-- Name: idx_pelayanan_nama; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pelayanan_nama ON public.pelayanan USING btree (nama_pelayanan);


--
-- Name: idx_pembayaran_tanggal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pembayaran_tanggal ON public.pembayaran USING btree (tanggal_pembayaran);


--
-- Name: idx_pemeriksaan_dokter; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pemeriksaan_dokter ON public.pemeriksaan USING btree (id_dokter);


--
-- Name: idx_penjualan_jenis; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_penjualan_jenis ON public.penjualan_obat USING btree (jenis_penjualan);


--
-- Name: idx_penjualan_tanggal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_penjualan_tanggal ON public.penjualan_obat USING btree (tanggal_penjualan);


--
-- Name: idx_pesanan_detail_pesanan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pesanan_detail_pesanan ON public.pesanan_online_detail USING btree (id_pesanan);


--
-- Name: idx_pesanan_pasien; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pesanan_pasien ON public.pesanan_online USING btree (id_pasien);


--
-- Name: idx_pesanan_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pesanan_status ON public.pesanan_online USING btree (status);


--
-- Name: idx_pesanan_tanggal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_pesanan_tanggal ON public.pesanan_online USING btree (tanggal_pesanan);


--
-- Name: idx_poli_nama; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_poli_nama ON public.poli USING btree (nama_poli);


--
-- Name: idx_resep_detail_obat; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resep_detail_obat ON public.resep_detail USING btree (id_obat);


--
-- Name: idx_resep_dokter; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resep_dokter ON public.resep USING btree (id_dokter);


--
-- Name: idx_resep_pasien; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_resep_pasien ON public.resep USING btree (id_pasien);


--
-- Name: idx_tagihan_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tagihan_status ON public.tagihan USING btree (status);


--
-- Name: idx_tagihan_tanggal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tagihan_tanggal ON public.tagihan USING btree (tanggal_tagihan);


--
-- Name: idx_tindakan_pemeriksaan; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tindakan_pemeriksaan ON public.tindakan USING btree (id_pemeriksaan);


--
-- Name: idx_transaksi_tanggal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_transaksi_tanggal ON public.transaksi USING btree (tanggal_transaksi);


--
-- Name: dokter dokter_id_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dokter
    ADD CONSTRAINT dokter_id_user_fkey FOREIGN KEY (id_user) REFERENCES public.users(id_user) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: antrian fk_antrian_kunjungan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.antrian
    ADD CONSTRAINT fk_antrian_kunjungan FOREIGN KEY (id_kunjungan) REFERENCES public.kunjungan(id_kunjungan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: audit_logs fk_audit_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT fk_audit_user FOREIGN KEY (id_user) REFERENCES public.users(id_user) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: diagnosis fk_diagnosis_pemeriksaan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.diagnosis
    ADD CONSTRAINT fk_diagnosis_pemeriksaan FOREIGN KEY (id_pemeriksaan) REFERENCES public.pemeriksaan(id_pemeriksaan) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: dokter fk_dokter_spesialis; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.dokter
    ADD CONSTRAINT fk_dokter_spesialis FOREIGN KEY (id_spesialis) REFERENCES public.spesialis(id_spesialis) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: kunjungan fk_kunjungan_dokter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kunjungan
    ADD CONSTRAINT fk_kunjungan_dokter FOREIGN KEY (id_dokter) REFERENCES public.dokter(id_dokter) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: kunjungan fk_kunjungan_pasien; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kunjungan
    ADD CONSTRAINT fk_kunjungan_pasien FOREIGN KEY (id_pasien) REFERENCES public.pasien(id_pasien) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: kunjungan fk_kunjungan_pelayanan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kunjungan
    ADD CONSTRAINT fk_kunjungan_pelayanan FOREIGN KEY (id_pelayanan) REFERENCES public.pelayanan(id_pelayanan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: kunjungan fk_kunjungan_poli; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kunjungan
    ADD CONSTRAINT fk_kunjungan_poli FOREIGN KEY (id_poli) REFERENCES public.poli(id_poli) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: kunjungan fk_kunjungan_ruangan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kunjungan
    ADD CONSTRAINT fk_kunjungan_ruangan FOREIGN KEY (id_ruangan) REFERENCES public.ruangan(id_ruangan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: mutasi_stok fk_mutasi_stok_obat; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mutasi_stok
    ADD CONSTRAINT fk_mutasi_stok_obat FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: pembayaran fk_pembayaran_transaksi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pembayaran
    ADD CONSTRAINT fk_pembayaran_transaksi FOREIGN KEY (id_transaksi) REFERENCES public.transaksi(id_transaksi) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: pemeriksaan fk_pemeriksaan_dokter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pemeriksaan
    ADD CONSTRAINT fk_pemeriksaan_dokter FOREIGN KEY (id_dokter) REFERENCES public.dokter(id_dokter) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: pemeriksaan fk_pemeriksaan_kunjungan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pemeriksaan
    ADD CONSTRAINT fk_pemeriksaan_kunjungan FOREIGN KEY (id_kunjungan) REFERENCES public.kunjungan(id_kunjungan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: penjualan_obat_detail fk_penjualan_detail_obat; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penjualan_obat_detail
    ADD CONSTRAINT fk_penjualan_detail_obat FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: penjualan_obat_detail fk_penjualan_detail_penjualan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penjualan_obat_detail
    ADD CONSTRAINT fk_penjualan_detail_penjualan FOREIGN KEY (id_penjualan) REFERENCES public.penjualan_obat(id_penjualan) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: penjualan_obat fk_penjualan_pasien; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penjualan_obat
    ADD CONSTRAINT fk_penjualan_pasien FOREIGN KEY (id_pasien) REFERENCES public.pasien(id_pasien) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: penjualan_obat fk_penjualan_resep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penjualan_obat
    ADD CONSTRAINT fk_penjualan_resep FOREIGN KEY (id_resep) REFERENCES public.resep(id_resep) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: resep_detail fk_resep_detail_obat; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep_detail
    ADD CONSTRAINT fk_resep_detail_obat FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: resep_detail fk_resep_detail_resep; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep_detail
    ADD CONSTRAINT fk_resep_detail_resep FOREIGN KEY (id_resep) REFERENCES public.resep(id_resep) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: resep fk_resep_dokter; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep
    ADD CONSTRAINT fk_resep_dokter FOREIGN KEY (id_dokter) REFERENCES public.dokter(id_dokter) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: resep fk_resep_pasien; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep
    ADD CONSTRAINT fk_resep_pasien FOREIGN KEY (id_pasien) REFERENCES public.pasien(id_pasien) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: resep fk_resep_pemeriksaan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.resep
    ADD CONSTRAINT fk_resep_pemeriksaan FOREIGN KEY (id_pemeriksaan) REFERENCES public.pemeriksaan(id_pemeriksaan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: role_permissions fk_role_permissions_permission; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fk_role_permissions_permission FOREIGN KEY (id_permission) REFERENCES public.permissions(id_permission) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: role_permissions fk_role_permissions_role; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT fk_role_permissions_role FOREIGN KEY (id_role) REFERENCES public.roles(id_role) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: ruangan fk_ruangan_poli; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ruangan
    ADD CONSTRAINT fk_ruangan_poli FOREIGN KEY (id_poli) REFERENCES public.poli(id_poli) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: stok_obat fk_stok_obat_obat; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.stok_obat
    ADD CONSTRAINT fk_stok_obat_obat FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: tagihan_detail fk_tagihan_detail_tagihan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tagihan_detail
    ADD CONSTRAINT fk_tagihan_detail_tagihan FOREIGN KEY (id_tagihan) REFERENCES public.tagihan(id_tagihan) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: tagihan fk_tagihan_kunjungan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tagihan
    ADD CONSTRAINT fk_tagihan_kunjungan FOREIGN KEY (id_kunjungan) REFERENCES public.kunjungan(id_kunjungan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: tindakan fk_tindakan_pemeriksaan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tindakan
    ADD CONSTRAINT fk_tindakan_pemeriksaan FOREIGN KEY (id_pemeriksaan) REFERENCES public.pemeriksaan(id_pemeriksaan) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: transaksi fk_transaksi_tagihan; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.transaksi
    ADD CONSTRAINT fk_transaksi_tagihan FOREIGN KEY (id_tagihan) REFERENCES public.tagihan(id_tagihan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: user_roles fk_user_roles_role; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_role FOREIGN KEY (id_role) REFERENCES public.roles(id_role) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: user_roles fk_user_roles_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fk_user_roles_user FOREIGN KEY (id_user) REFERENCES public.users(id_user) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: pasien pasien_id_user_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pasien
    ADD CONSTRAINT pasien_id_user_fkey FOREIGN KEY (id_user) REFERENCES public.users(id_user) ON UPDATE CASCADE ON DELETE SET NULL;


--
-- Name: penerimaan_obat_detail penerimaan_obat_detail_id_obat_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penerimaan_obat_detail
    ADD CONSTRAINT penerimaan_obat_detail_id_obat_fkey FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat);


--
-- Name: penerimaan_obat_detail penerimaan_obat_detail_id_penerimaan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penerimaan_obat_detail
    ADD CONSTRAINT penerimaan_obat_detail_id_penerimaan_fkey FOREIGN KEY (id_penerimaan) REFERENCES public.penerimaan_obat(id_penerimaan) ON DELETE CASCADE;


--
-- Name: penerimaan_obat penerimaan_obat_id_pengadaan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.penerimaan_obat
    ADD CONSTRAINT penerimaan_obat_id_pengadaan_fkey FOREIGN KEY (id_pengadaan) REFERENCES public.pengadaan_obat(id_pengadaan);


--
-- Name: pengadaan_obat_detail pengadaan_obat_detail_id_obat_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengadaan_obat_detail
    ADD CONSTRAINT pengadaan_obat_detail_id_obat_fkey FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat);


--
-- Name: pengadaan_obat_detail pengadaan_obat_detail_id_pengadaan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengadaan_obat_detail
    ADD CONSTRAINT pengadaan_obat_detail_id_pengadaan_fkey FOREIGN KEY (id_pengadaan) REFERENCES public.pengadaan_obat(id_pengadaan) ON DELETE CASCADE;


--
-- Name: pengadaan_obat pengadaan_obat_id_supplier_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pengadaan_obat
    ADD CONSTRAINT pengadaan_obat_id_supplier_fkey FOREIGN KEY (id_supplier) REFERENCES public.supplier(id_supplier);


--
-- Name: pesanan_online_detail pesanan_online_detail_id_obat_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online_detail
    ADD CONSTRAINT pesanan_online_detail_id_obat_fkey FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: pesanan_online_detail pesanan_online_detail_id_pesanan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online_detail
    ADD CONSTRAINT pesanan_online_detail_id_pesanan_fkey FOREIGN KEY (id_pesanan) REFERENCES public.pesanan_online(id_pesanan) ON UPDATE CASCADE ON DELETE CASCADE;


--
-- Name: pesanan_online_detail pesanan_online_detail_id_resep_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online_detail
    ADD CONSTRAINT pesanan_online_detail_id_resep_fkey FOREIGN KEY (id_resep) REFERENCES public.resep(id_resep) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: pesanan_online pesanan_online_id_pasien_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online
    ADD CONSTRAINT pesanan_online_id_pasien_fkey FOREIGN KEY (id_pasien) REFERENCES public.pasien(id_pasien) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: pesanan_online pesanan_online_id_penjualan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online
    ADD CONSTRAINT pesanan_online_id_penjualan_fkey FOREIGN KEY (id_penjualan) REFERENCES public.penjualan_obat(id_penjualan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: pesanan_online pesanan_online_id_tagihan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pesanan_online
    ADD CONSTRAINT pesanan_online_id_tagihan_fkey FOREIGN KEY (id_tagihan) REFERENCES public.tagihan(id_tagihan) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- Name: retur_pengadaan_detail retur_pengadaan_detail_id_obat_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retur_pengadaan_detail
    ADD CONSTRAINT retur_pengadaan_detail_id_obat_fkey FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat);


--
-- Name: retur_pengadaan_detail retur_pengadaan_detail_id_retur_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retur_pengadaan_detail
    ADD CONSTRAINT retur_pengadaan_detail_id_retur_fkey FOREIGN KEY (id_retur) REFERENCES public.retur_pengadaan(id_retur) ON DELETE CASCADE;


--
-- Name: retur_pengadaan retur_pengadaan_id_penerimaan_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.retur_pengadaan
    ADD CONSTRAINT retur_pengadaan_id_penerimaan_fkey FOREIGN KEY (id_penerimaan) REFERENCES public.penerimaan_obat(id_penerimaan);


--
-- PostgreSQL database dump complete
--

\unrestrict ybrW0HOQop4Yd9cKtIHKaeP0jflV32COkwkokwFyNmsX5kcMHiNoYqa7pgVftfB


-- Bagian B : SEED minimal
--
-- PostgreSQL database dump
--

\restrict N7pSzXqag1CGl5FlWIegvonplApTCoQiY8gLd8UFleUbxe3ahHMsEtgIe4ucFRa

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Data for Name: spesialis; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.spesialis (id_spesialis, nama_spesialis, status) VALUES (1, 'Penyakit Dalam', 'AKTIF');
INSERT INTO public.spesialis (id_spesialis, nama_spesialis, status) VALUES (4, 'Test Audit Spesialis', 'AKTIF');


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.users (id_user, username, password, nama, status, created_at, updated_at) VALUES (1, 'admin', '$2a$08$9dMzZCuGiZCEoyeLrM/ztuYIgIERYcjL7ez5BPmHT7oVqbAA9EX26', 'Administrator', 'AKTIF', '2026-09-17 12:06:53.277526', '2026-09-17 12:06:53.277526');
INSERT INTO public.users (id_user, username, password, nama, status, created_at, updated_at) VALUES (2, 'pelayanan', '$2a$08$9dMzZCuGiZCEoyeLrM/ztuYIgIERYcjL7ez5BPmHT7oVqbAA9EX26', 'Petugas Pelayanan', 'AKTIF', '2026-09-17 12:06:53.277526', '2026-09-17 12:06:53.277526');
INSERT INTO public.users (id_user, username, password, nama, status, created_at, updated_at) VALUES (3, 'dokter', '$2a$08$9dMzZCuGiZCEoyeLrM/ztuYIgIERYcjL7ez5BPmHT7oVqbAA9EX26', 'dr. Contoh', 'AKTIF', '2026-09-17 12:06:53.277526', '2026-09-17 12:06:53.277526');
INSERT INTO public.users (id_user, username, password, nama, status, created_at, updated_at) VALUES (4, 'apoteker', '$2a$08$9dMzZCuGiZCEoyeLrM/ztuYIgIERYcjL7ez5BPmHT7oVqbAA9EX26', 'Apt. Contoh', 'AKTIF', '2026-09-17 12:06:53.277526', '2026-09-17 12:06:53.277526');
INSERT INTO public.users (id_user, username, password, nama, status, created_at, updated_at) VALUES (5, 'pasien', '$2a$08$9dMzZCuGiZCEoyeLrM/ztuYIgIERYcjL7ez5BPmHT7oVqbAA9EX26', 'Pasien Contoh', 'AKTIF', '2026-09-17 12:06:53.277526', '2026-09-17 12:06:53.277526');


--
-- Data for Name: dokter; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.dokter (id_dokter, id_spesialis, nama_dokter, no_sip, no_hp, tarif, status, created_at, updated_at, id_user) VALUES (1, 1, 'dr. Contoh', 'SIP-001', NULL, 75000.00, 'AKTIF', '2026-09-17 13:09:44.09408', '2026-09-17 13:54:17', 3);


--
-- Data for Name: obat; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.obat (id_obat, kode_obat, nama_obat, jenis_obat, satuan, harga, stok_minimum, wajib_resep, status, created_at, updated_at) VALUES (2, 'OBT-002', 'Amoxicillin 500mg', NULL, 'kapsul', 5000.00, 10, true, 'AKTIF', '2026-09-17 13:09:44.104576', '2026-09-17 13:09:44.104576');
INSERT INTO public.obat (id_obat, kode_obat, nama_obat, jenis_obat, satuan, harga, stok_minimum, wajib_resep, status, created_at, updated_at) VALUES (1, 'OBT-001', 'Paracetamol 500mg', NULL, 'tablet', 2000.00, 10, false, 'AKTIF', '2026-09-17 13:09:44.104576', '2026-09-17 13:09:44.104576');
INSERT INTO public.obat (id_obat, kode_obat, nama_obat, jenis_obat, satuan, harga, stok_minimum, wajib_resep, status, created_at, updated_at) VALUES (4, 'OBT-F-NON', 'Non Resep F', NULL, 'tablet', 1000.00, 5, false, 'AKTIF', '2026-09-17 14:40:38.332077', '2026-09-17 14:40:38.332077');
INSERT INTO public.obat (id_obat, kode_obat, nama_obat, jenis_obat, satuan, harga, stok_minimum, wajib_resep, status, created_at, updated_at) VALUES (5, 'OBT-F-WAJIB', 'Wajib Resep F', NULL, 'kapsul', 2000.00, 5, true, 'AKTIF', '2026-09-17 14:40:38.332077', '2026-09-17 14:40:38.332077');


--
-- Data for Name: pasien; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pasien (id_pasien, no_rm, nik, nama, tanggal_lahir, jenis_kelamin, alamat, no_hp, status, created_at, updated_at, id_user) VALUES (5, 'RM-000001', NULL, 'Pasien Contoh', NULL, 'L', NULL, NULL, 'AKTIF', '2026-09-17 22:51:07.208175', '2026-09-17 22:51:07.208175', 5);


--
-- Data for Name: pelayanan; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.pelayanan (id_pelayanan, nama_pelayanan, jenis_pelayanan, tarif, status) VALUES (1, 'Poli Umum', 'Rawat Jalan', 50000.00, 'AKTIF');
INSERT INTO public.pelayanan (id_pelayanan, nama_pelayanan, jenis_pelayanan, tarif, status) VALUES (5, 'Test Audit Pelayanan', 'Laboratorium', 50000.00, 'AKTIF');


--
-- Data for Name: permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (1, 'lihat_dashboard', 'DASHBOARD');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (2, 'kelola_pendaftaran', 'PELAYANAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (3, 'kelola_pasien', 'PELAYANAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (4, 'kelola_antrian', 'PELAYANAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (5, 'kelola_antrian_dokter', 'PEMERIKSAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (6, 'kelola_pemeriksaan', 'PEMERIKSAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (7, 'lihat_rekam_medis', 'PEMERIKSAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (8, 'kelola_resep', 'APOTEK');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (9, 'kelola_penjualan_obat', 'APOTEK');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (10, 'kelola_stok_obat', 'APOTEK');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (11, 'kelola_mutasi_stok', 'APOTEK');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (12, 'kelola_transaksi', 'TRANSAKSI');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (13, 'kelola_tagihan', 'TRANSAKSI');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (14, 'kelola_pembayaran', 'TRANSAKSI');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (15, 'lihat_laporan', 'LAPORAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (16, 'kelola_master_data', 'MASTER_DATA');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (17, 'kelola_user', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (18, 'kelola_role_permission', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (19, 'kelola_pengaturan', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (20, 'lihat_audit_log', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (21, 'kelola_pengadaan', 'PENGADAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (22, 'Master.Master.View', 'MASTER');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (33, 'Site.Master.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (34, 'Site.Reports.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (35, 'Site.Settings.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (36, 'Site.Developer.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (37, 'Site.Pelayanan.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (38, 'Site.Pemeriksaan.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (39, 'Site.Apotek.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (40, 'Site.Transaksi.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (41, 'Site.Laporan.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (42, 'Pasien.Pelayanan.View', 'PELAYANAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (43, 'Kunjungan.Pelayanan.View', 'PELAYANAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (44, 'Antrian.Pelayanan.View', 'PELAYANAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (45, 'Antrian.Pemeriksaan.View', 'PEMERIKSAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (46, 'Pemeriksaan.Pemeriksaan.View', 'PEMERIKSAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (47, 'Resep.Pemeriksaan.View', 'PEMERIKSAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (48, 'Resep.Apotek.View', 'APOTEK');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (49, 'Penjualan.Apotek.View', 'APOTEK');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (50, 'Stok.Apotek.View', 'APOTEK');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (51, 'Pengadaan.Apotek.View', 'PENGADAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (52, 'Pengadaan.Master.View', 'PENGADAAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (53, 'Tagihan.Transaksi.View', 'TRANSAKSI');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (54, 'Transaksi.Transaksi.View', 'TRANSAKSI');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (55, 'Laporan.Laporan.View', 'LAPORAN');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (56, 'Audit.Settings.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (57, 'Bonfire.Users.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (58, 'Bonfire.Users.Manage', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (59, 'Bonfire.Users.Add', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (60, 'Bonfire.Roles.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (61, 'Bonfire.Roles.Manage', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (62, 'Bonfire.Roles.Add', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (64, 'belanja_online', 'APOTEK_ONLINE');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (65, 'kelola_pesanan_online', 'APOTEK_ONLINE');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (66, 'Site.Online.View', 'MANAJEMEN_SISTEM');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (67, 'Apotekonline.Online.View', 'APOTEK_ONLINE');
INSERT INTO public.permissions (id_permission, nama_permission, modul) VALUES (68, 'Apotekonline.Apotek.View', 'APOTEK_ONLINE');


--
-- Data for Name: poli; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.poli (id_poli, nama_poli, status) VALUES (1, 'Poli Umum', 'AKTIF');
INSERT INTO public.poli (id_poli, nama_poli, status) VALUES (4, 'Test Audit Poli', 'AKTIF');


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.roles (id_role, nama_role) VALUES (1, 'PASIEN');
INSERT INTO public.roles (id_role, nama_role) VALUES (2, 'ADMIN_PELAYANAN');
INSERT INTO public.roles (id_role, nama_role) VALUES (3, 'DOKTER');
INSERT INTO public.roles (id_role, nama_role) VALUES (4, 'APOTEKER');


--
-- Data for Name: role_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 1);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 2);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 3);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 4);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 5);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 6);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 7);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 8);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 9);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 10);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 11);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 12);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 13);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 14);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 15);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 16);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 17);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 18);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 19);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 20);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 1);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 5);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 6);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 7);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 8);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 1);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 8);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 9);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 10);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 11);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (1, 1);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 21);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 21);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 22);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 22);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 16);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 33);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 33);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 34);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 35);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 15);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 37);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 38);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 38);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 39);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 39);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 40);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 41);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 41);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 42);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 43);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 44);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 45);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 45);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 46);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 46);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 47);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (3, 47);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 48);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 48);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 49);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 49);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 50);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 50);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 51);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 51);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 52);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 52);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 53);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 54);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 55);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 55);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 56);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 57);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 58);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 59);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 60);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 61);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (2, 62);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (1, 64);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 65);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (1, 66);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (1, 67);
INSERT INTO public.role_permissions (id_role, id_permission) VALUES (4, 68);


--
-- Data for Name: ruangan; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.ruangan (id_ruangan, id_poli, nama_ruangan, status) VALUES (1, 1, 'Ruang Periksa 1', 'AKTIF');
INSERT INTO public.ruangan (id_ruangan, id_poli, nama_ruangan, status) VALUES (4, NULL, 'Test Audit Ruangan', 'AKTIF');


--
-- Data for Name: stok_obat; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.stok_obat (id_stok, id_obat, jumlah_stok, updated_at) VALUES (1, 1, 100, '2026-09-17 23:37:43');
INSERT INTO public.stok_obat (id_stok, id_obat, jumlah_stok, updated_at) VALUES (3, 2, 50, '2026-09-17 23:33:18');


--
-- Data for Name: supplier; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.supplier (id_supplier, kode_supplier, nama_supplier, alamat, no_hp, status, created_at, updated_at) VALUES (2, 'SUP-001', 'PT Pharma Jaya', 'Jl. Industri No. 10', '081234567890', 'AKTIF', '2026-09-17 15:17:48', '2026-09-17 15:17:48.332063');


--
-- Data for Name: user_roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

INSERT INTO public.user_roles (id_user, id_role) VALUES (1, 2);
INSERT INTO public.user_roles (id_user, id_role) VALUES (2, 2);
INSERT INTO public.user_roles (id_user, id_role) VALUES (3, 3);
INSERT INTO public.user_roles (id_user, id_role) VALUES (4, 4);
INSERT INTO public.user_roles (id_user, id_role) VALUES (5, 1);


--
-- Name: dokter_id_dokter_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.dokter_id_dokter_seq', 5, true);


--
-- Name: obat_id_obat_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.obat_id_obat_seq', 5, true);


--
-- Name: pasien_id_pasien_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pasien_id_pasien_seq', 7, true);


--
-- Name: pelayanan_id_pelayanan_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pelayanan_id_pelayanan_seq', 5, true);


--
-- Name: permissions_id_permission_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.permissions_id_permission_seq', 68, true);


--
-- Name: poli_id_poli_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.poli_id_poli_seq', 4, true);


--
-- Name: roles_id_role_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_role_seq', 4, true);


--
-- Name: ruangan_id_ruangan_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ruangan_id_ruangan_seq', 4, true);


--
-- Name: spesialis_id_spesialis_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.spesialis_id_spesialis_seq', 4, true);


--
-- Name: stok_obat_id_stok_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stok_obat_id_stok_seq', 3, true);


--
-- Name: supplier_id_supplier_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.supplier_id_supplier_seq', 3, true);


--
-- Name: users_id_user_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_user_seq', 6, true);


--
-- PostgreSQL database dump complete
--

\unrestrict N7pSzXqag1CGl5FlWIegvonplApTCoQiY8gLd8UFleUbxe3ahHMsEtgIe4ucFRa


-- Bagian C : sinkron sequence identity (hindari PK clash setelah seed)
SELECT setval(pg_get_serial_sequence('public.roles','id_role'), COALESCE((SELECT MAX(id_role) FROM public.roles), 1), false);
SELECT setval(pg_get_serial_sequence('public.permissions','id_permission'), COALESCE((SELECT MAX(id_permission) FROM public.permissions), 1), false);
SELECT setval(pg_get_serial_sequence('public.users','id_user'), COALESCE((SELECT MAX(id_user) FROM public.users), 1), false);
SELECT setval(pg_get_serial_sequence('public.spesialis','id_spesialis'), COALESCE((SELECT MAX(id_spesialis) FROM public.spesialis), 1), false);
SELECT setval(pg_get_serial_sequence('public.pelayanan','id_pelayanan'), COALESCE((SELECT MAX(id_pelayanan) FROM public.pelayanan), 1), false);
SELECT setval(pg_get_serial_sequence('public.poli','id_poli'), COALESCE((SELECT MAX(id_poli) FROM public.poli), 1), false);
SELECT setval(pg_get_serial_sequence('public.ruangan','id_ruangan'), COALESCE((SELECT MAX(id_ruangan) FROM public.ruangan), 1), false);
SELECT setval(pg_get_serial_sequence('public.dokter','id_dokter'), COALESCE((SELECT MAX(id_dokter) FROM public.dokter), 1), false);
SELECT setval(pg_get_serial_sequence('public.obat','id_obat'), COALESCE((SELECT MAX(id_obat) FROM public.obat), 1), false);
SELECT setval(pg_get_serial_sequence('public.stok_obat','id_stok'), COALESCE((SELECT MAX(id_stok) FROM public.stok_obat), 1), false);
SELECT setval(pg_get_serial_sequence('public.supplier','id_supplier'), COALESCE((SELECT MAX(id_supplier) FROM public.supplier), 1), false);
SELECT setval(pg_get_serial_sequence('public.pasien','id_pasien'), COALESCE((SELECT MAX(id_pasien) FROM public.pasien), 1), false);
SELECT setval(pg_get_serial_sequence('public.pesanan_online','id_pesanan'), COALESCE((SELECT MAX(id_pesanan) FROM public.pesanan_online), 1), false);
