-- ==========================================================================
-- Buat tabel permintaan pengadaan + detail + log status (dari migration 010)
-- ==========================================================================

CREATE TABLE IF NOT EXISTS permintaan_pengadaan (
    id_permintaan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_permintaan VARCHAR(50) NOT NULL UNIQUE,
    tanggal_permintaan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_pemohon BIGINT REFERENCES users(id_user),
    unit VARCHAR(100) NOT NULL DEFAULT 'APOTEK',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT'
        CHECK (status IN ('DRAFT','DIAJUKAN','DISETUJUI','DIPROSES','SELESAI','DITOLAK','DIBATALKAN')),
    catatan TEXT,
    disetujui_oleh BIGINT REFERENCES users(id_user),
    tanggal_persetujuan TIMESTAMP,
    catatan_persetujuan TEXT,
    dibuat_oleh BIGINT REFERENCES users(id_user),
    diubah_oleh BIGINT REFERENCES users(id_user),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS permintaan_pengadaan_detail (
    id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_permintaan BIGINT NOT NULL REFERENCES permintaan_pengadaan(id_permintaan) ON DELETE CASCADE,
    id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
    satuan VARCHAR(50),
    harga_referensi NUMERIC(15,2) NOT NULL DEFAULT 0,
    stok_saat_minta INTEGER NOT NULL DEFAULT 0,
    jumlah_minta INTEGER NOT NULL CHECK (jumlah_minta > 0),
    catatan TEXT,
    UNIQUE (id_permintaan, id_obat)
);

CREATE TABLE IF NOT EXISTS permintaan_status_log (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_permintaan BIGINT NOT NULL REFERENCES permintaan_pengadaan(id_permintaan) ON DELETE CASCADE,
    status_lama VARCHAR(20),
    status_baru VARCHAR(20) NOT NULL,
    id_user BIGINT REFERENCES users(id_user),
    tanggal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    catatan TEXT
);

CREATE INDEX IF NOT EXISTS idx_permintaan_status ON permintaan_pengadaan (status);

-- Tambahkan kolom id_permintaan ke pengadaan_obat agar PO dapat merujuk permintaan
ALTER TABLE pengadaan_obat
    ADD COLUMN IF NOT EXISTS id_permintaan BIGINT REFERENCES permintaan_pengadaan(id_permintaan);

-- Tambahkan tabel stok_batch jika belum ada (juga dari migration 010)
CREATE TABLE IF NOT EXISTS stok_batch (
    id_batch BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_obat BIGINT NOT NULL REFERENCES obat(id_obat) ON DELETE RESTRICT,
    nomor_batch VARCHAR(100),
    tanggal_kadaluarsa DATE,
    jumlah INTEGER NOT NULL DEFAULT 0 CHECK (jumlah >= 0),
    dibuat_oleh BIGINT REFERENCES users(id_user),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_stok_batch_obat ON stok_batch (id_obat);
CREATE INDEX IF NOT EXISTS idx_stok_batch_ed ON stok_batch (tanggal_kadaluarsa);

-- Kolom mutasi_stok yang diperkaya
ALTER TABLE mutasi_stok
    ADD COLUMN IF NOT EXISTS id_batch BIGINT REFERENCES stok_batch(id_batch),
    ADD COLUMN IF NOT EXISTS saldo INTEGER,
    ADD COLUMN IF NOT EXISTS id_user BIGINT REFERENCES users(id_user);

-- Permissions untuk alur persediaan
INSERT INTO permissions (nama_permission, modul)
    VALUES ('kelola_permintaan', 'PERSEDIAAN'),
           ('setujui_permintaan', 'PERSEDIAAN'),
           ('kelola_penerimaan', 'PERSEDIAAN'),
           ('konfirmasi_penerimaan', 'PERSEDIAAN'),
           ('kelola_retur_pembelian', 'PERSEDIAAN')
    ON CONFLICT (nama_permission) DO NOTHING;

-- Berikan permission tersebut ke semua role yang sudah punya kelola_pengadaan
INSERT INTO role_permissions (id_role, id_permission)
    SELECT DISTINCT r.id_role, p.id_permission
    FROM roles r
    JOIN role_permissions rp ON rp.id_role = r.id_role
    JOIN permissions kelola ON kelola.id_permission = rp.id_permission
        AND kelola.nama_permission = 'kelola_pengadaan'
    JOIN permissions p ON p.nama_permission IN
        ('kelola_permintaan','setujui_permintaan','kelola_penerimaan',
         'konfirmasi_penerimaan','kelola_retur_pembelian')
    WHERE NOT EXISTS (
        SELECT 1 FROM role_permissions x
        WHERE x.id_role = r.id_role AND x.id_permission = p.id_permission
    );
