-- =====================================================================
-- UPDATE incremental untuk database teman (yang SUDAH berisi data lama).
-- Sifat: IDEMPOTEN â€” aman dijalankan berulang; data/tabel lama TIDAK
-- dihapus dan TIDAK diubah, hanya MENAMBAHKAN yang belum ada.
-- Asumsi: database bernama apotek dengan struktur versi lama
-- (sebelum tabel pengadaan + kolom dokter.id_user/pasien.id_user +
-- permission View per-context). Untuk database KOSONG gunakan
-- database/apotek_latest.sql, BUKAN file ini.
-- Cara pakai:
--   psql -U postgres -d apotek -v ON_ERROR_STOP=1 -f database/update_dari_versi_lama.sql
-- Isi:
--   1. Tabel pengadaan (7 tabel, IF NOT EXISTS + constraint DO-block)
--   2. Kolom dokter.id_user & pasien.id_user (IF NOT EXISTS)
--   3. Permission View per-context + Bonfire (ON CONFLICT DO NOTHING)
--   4. Grants per role berbasis NAMA (ON CONFLICT DO NOTHING)
--   5. Bersih-bersih permission View usang (aman: WHERE + hanya baris itu)
--   6. Seed portal pasien (hanya bila user id 5 ada & belum punya pasien)
--   7. Sinkron sequence (MAX, aman di semua kondisi)
-- CATATAN PENTING:
--   - Grants memakai nama_role (ADMIN_PELAYANAN/DOKTER/APOTEKER). Bila nama
--     role di tempat teman berbeda, sesuaikan Bagian 4.
--   - Setelah update, user DOKTER harus dipetakan: UPDATE dokter SET
--     id_user = <id user dokter> WHERE ...; (portal pasien butuh
--     pasien.id_user yang menunjuk user pasiennya).
-- =====================================================================

-- Bagian 1 : tabel pengadaan (baru seluruhnya) -------------------------
CREATE TABLE IF NOT EXISTS public.penerimaan_obat (
    id_penerimaan bigint NOT NULL,
    id_pengadaan bigint NOT NULL,
    nomor_penerimaan character varying(50) NOT NULL,
    tanggal_terima timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(30) DEFAULT 'Sesuai'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);



CREATE TABLE IF NOT EXISTS public.penerimaan_obat_detail (
    id_detail bigint NOT NULL,
    id_penerimaan bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah_terima integer NOT NULL,
    kondisi character varying(30) DEFAULT 'Baik'::character varying NOT NULL
);



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'penerimaan_obat_detail_id_detail_seq') THEN ALTER TABLE public.penerimaan_obat_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penerimaan_obat_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
); END IF; END $$;;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'penerimaan_obat_id_penerimaan_seq') THEN ALTER TABLE public.penerimaan_obat ALTER COLUMN id_penerimaan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penerimaan_obat_id_penerimaan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
); END IF; END $$;;



CREATE TABLE IF NOT EXISTS public.pengadaan_obat (
    id_pengadaan bigint NOT NULL,
    nomor_pengadaan character varying(50) NOT NULL,
    id_supplier bigint NOT NULL,
    tanggal_pesanan timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    total numeric DEFAULT 0 NOT NULL,
    status character varying(30) DEFAULT 'Dipesan'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);



CREATE TABLE IF NOT EXISTS public.pengadaan_obat_detail (
    id_detail bigint NOT NULL,
    id_pengadaan bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah_pesan integer NOT NULL,
    harga numeric NOT NULL,
    subtotal numeric NOT NULL
);



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pengadaan_obat_detail_id_detail_seq') THEN ALTER TABLE public.pengadaan_obat_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pengadaan_obat_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
); END IF; END $$;;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'pengadaan_obat_id_pengadaan_seq') THEN ALTER TABLE public.pengadaan_obat ALTER COLUMN id_pengadaan ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pengadaan_obat_id_pengadaan_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
); END IF; END $$;;



CREATE TABLE IF NOT EXISTS public.retur_pengadaan (
    id_retur bigint NOT NULL,
    id_penerimaan bigint NOT NULL,
    nomor_retur character varying(50) NOT NULL,
    tanggal_retur timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    status character varying(30) DEFAULT 'Diajukan'::character varying NOT NULL,
    keterangan text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);



CREATE TABLE IF NOT EXISTS public.retur_pengadaan_detail (
    id_detail bigint NOT NULL,
    id_retur bigint NOT NULL,
    id_obat bigint NOT NULL,
    jumlah integer NOT NULL,
    alasan text
);



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'retur_pengadaan_detail_id_detail_seq') THEN ALTER TABLE public.retur_pengadaan_detail ALTER COLUMN id_detail ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retur_pengadaan_detail_id_detail_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
); END IF; END $$;;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'retur_pengadaan_id_retur_seq') THEN ALTER TABLE public.retur_pengadaan ALTER COLUMN id_retur ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retur_pengadaan_id_retur_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
); END IF; END $$;;



CREATE TABLE IF NOT EXISTS public.supplier (
    id_supplier bigint NOT NULL,
    kode_supplier character varying(50) NOT NULL,
    nama_supplier character varying(150) NOT NULL,
    alamat text,
    no_hp character varying(20),
    status character varying(20) DEFAULT 'AKTIF'::character varying NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = 'supplier_id_supplier_seq') THEN ALTER TABLE public.supplier ALTER COLUMN id_supplier ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.supplier_id_supplier_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
); END IF; END $$;;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'penerimaan_obat_detail_pkey') THEN ALTER TABLE ONLY public.penerimaan_obat_detail ADD CONSTRAINT penerimaan_obat_detail_pkey PRIMARY KEY (id_detail); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'penerimaan_obat_nomor_penerimaan_key') THEN ALTER TABLE ONLY public.penerimaan_obat ADD CONSTRAINT penerimaan_obat_nomor_penerimaan_key UNIQUE (nomor_penerimaan); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'penerimaan_obat_pkey') THEN ALTER TABLE ONLY public.penerimaan_obat ADD CONSTRAINT penerimaan_obat_pkey PRIMARY KEY (id_penerimaan); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pengadaan_obat_detail_pkey') THEN ALTER TABLE ONLY public.pengadaan_obat_detail ADD CONSTRAINT pengadaan_obat_detail_pkey PRIMARY KEY (id_detail); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pengadaan_obat_nomor_pengadaan_key') THEN ALTER TABLE ONLY public.pengadaan_obat ADD CONSTRAINT pengadaan_obat_nomor_pengadaan_key UNIQUE (nomor_pengadaan); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pengadaan_obat_pkey') THEN ALTER TABLE ONLY public.pengadaan_obat ADD CONSTRAINT pengadaan_obat_pkey PRIMARY KEY (id_pengadaan); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retur_pengadaan_detail_pkey') THEN ALTER TABLE ONLY public.retur_pengadaan_detail ADD CONSTRAINT retur_pengadaan_detail_pkey PRIMARY KEY (id_detail); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retur_pengadaan_nomor_retur_key') THEN ALTER TABLE ONLY public.retur_pengadaan ADD CONSTRAINT retur_pengadaan_nomor_retur_key UNIQUE (nomor_retur); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retur_pengadaan_pkey') THEN ALTER TABLE ONLY public.retur_pengadaan ADD CONSTRAINT retur_pengadaan_pkey PRIMARY KEY (id_retur); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'supplier_kode_supplier_key') THEN ALTER TABLE ONLY public.supplier ADD CONSTRAINT supplier_kode_supplier_key UNIQUE (kode_supplier); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'supplier_pkey') THEN ALTER TABLE ONLY public.supplier ADD CONSTRAINT supplier_pkey PRIMARY KEY (id_supplier); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'penerimaan_obat_detail_id_obat_fkey') THEN ALTER TABLE ONLY public.penerimaan_obat_detail ADD CONSTRAINT penerimaan_obat_detail_id_obat_fkey FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'penerimaan_obat_detail_id_penerimaan_fkey') THEN ALTER TABLE ONLY public.penerimaan_obat_detail ADD CONSTRAINT penerimaan_obat_detail_id_penerimaan_fkey FOREIGN KEY (id_penerimaan) REFERENCES public.penerimaan_obat(id_penerimaan) ON DELETE CASCADE; END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'penerimaan_obat_id_pengadaan_fkey') THEN ALTER TABLE ONLY public.penerimaan_obat ADD CONSTRAINT penerimaan_obat_id_pengadaan_fkey FOREIGN KEY (id_pengadaan) REFERENCES public.pengadaan_obat(id_pengadaan); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pengadaan_obat_detail_id_obat_fkey') THEN ALTER TABLE ONLY public.pengadaan_obat_detail ADD CONSTRAINT pengadaan_obat_detail_id_obat_fkey FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pengadaan_obat_detail_id_pengadaan_fkey') THEN ALTER TABLE ONLY public.pengadaan_obat_detail ADD CONSTRAINT pengadaan_obat_detail_id_pengadaan_fkey FOREIGN KEY (id_pengadaan) REFERENCES public.pengadaan_obat(id_pengadaan) ON DELETE CASCADE; END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'pengadaan_obat_id_supplier_fkey') THEN ALTER TABLE ONLY public.pengadaan_obat ADD CONSTRAINT pengadaan_obat_id_supplier_fkey FOREIGN KEY (id_supplier) REFERENCES public.supplier(id_supplier); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retur_pengadaan_detail_id_obat_fkey') THEN ALTER TABLE ONLY public.retur_pengadaan_detail ADD CONSTRAINT retur_pengadaan_detail_id_obat_fkey FOREIGN KEY (id_obat) REFERENCES public.obat(id_obat); END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retur_pengadaan_detail_id_retur_fkey') THEN ALTER TABLE ONLY public.retur_pengadaan_detail ADD CONSTRAINT retur_pengadaan_detail_id_retur_fkey FOREIGN KEY (id_retur) REFERENCES public.retur_pengadaan(id_retur) ON DELETE CASCADE; END IF; END $$;



DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'retur_pengadaan_id_penerimaan_fkey') THEN ALTER TABLE ONLY public.retur_pengadaan ADD CONSTRAINT retur_pengadaan_id_penerimaan_fkey FOREIGN KEY (id_penerimaan) REFERENCES public.penerimaan_obat(id_penerimaan); END IF; END $$;




-- Bagian 2 : kolom relasi user (migrasi 002 & 003) ---------------------
ALTER TABLE public.dokter ADD COLUMN IF NOT EXISTS id_user BIGINT REFERENCES public.users(id_user) ON UPDATE CASCADE ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_dokter_user ON public.dokter(id_user);
ALTER TABLE public.pasien ADD COLUMN IF NOT EXISTS id_user BIGINT REFERENCES public.users(id_user) ON UPDATE CASCADE ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_pasien_user ON public.pasien(id_user);

-- Bagian 3 : permission baru (ON CONFLICT = lewati bila sudah ada) -----
INSERT INTO public.permissions (nama_permission, modul) VALUES
('Site.Pelayanan.View','MANAJEMEN_SISTEM'),('Site.Pemeriksaan.View','MANAJEMEN_SISTEM'),
('Site.Apotek.View','MANAJEMEN_SISTEM'),('Site.Transaksi.View','MANAJEMEN_SISTEM'),
('Site.Laporan.View','MANAJEMEN_SISTEM'),('Site.Developer.View','MANAJEMEN_SISTEM'),
('Pasien.Pelayanan.View','PELAYANAN'),('Kunjungan.Pelayanan.View','PELAYANAN'),
('Antrian.Pelayanan.View','PELAYANAN'),('Antrian.Pemeriksaan.View','PEMERIKSAAN'),
('Pemeriksaan.Pemeriksaan.View','PEMERIKSAAN'),('Resep.Pemeriksaan.View','PEMERIKSAAN'),
('Resep.Apotek.View','APOTEK'),('Penjualan.Apotek.View','APOTEK'),('Stok.Apotek.View','APOTEK'),
('Pengadaan.Apotek.View','PENGADAAN'),('Pengadaan.Master.View','PENGADAAN'),
('Tagihan.Transaksi.View','TRANSAKSI'),('Transaksi.Transaksi.View','TRANSAKSI'),
('Laporan.Laporan.View','LAPORAN'),('Audit.Settings.View','MANAJEMEN_SISTEM'),
('Bonfire.Users.View','MANAJEMEN_SISTEM'),('Bonfire.Users.Manage','MANAJEMEN_SISTEM'),
('Bonfire.Users.Add','MANAJEMEN_SISTEM'),('Bonfire.Roles.View','MANAJEMEN_SISTEM'),
('Bonfire.Roles.Manage','MANAJEMEN_SISTEM'),('Bonfire.Roles.Add','MANAJEMEN_SISTEM')
ON CONFLICT (nama_permission) DO NOTHING;

-- Bagian 4 : grants per role (berbasis NAMA role + permission) ---------
INSERT INTO public.role_permissions (id_role, id_permission)
SELECT r.id_role, p.id_permission FROM public.permissions p JOIN public.roles r ON
(r.nama_role='ADMIN_PELAYANAN' AND p.nama_permission IN ('Site.Pelayanan.View','Site.Pemeriksaan.View','Site.Apotek.View','Site.Transaksi.View','Site.Laporan.View','Pasien.Pelayanan.View','Kunjungan.Pelayanan.View','Antrian.Pelayanan.View','Antrian.Pemeriksaan.View','Pemeriksaan.Pemeriksaan.View','Resep.Pemeriksaan.View','Resep.Apotek.View','Penjualan.Apotek.View','Stok.Apotek.View','Pengadaan.Apotek.View','Pengadaan.Master.View','Tagihan.Transaksi.View','Transaksi.Transaksi.View','Laporan.Laporan.View','Audit.Settings.View','Bonfire.Users.View','Bonfire.Users.Manage','Bonfire.Users.Add','Bonfire.Roles.View','Bonfire.Roles.Manage','Bonfire.Roles.Add'))
OR (r.nama_role='DOKTER' AND p.nama_permission IN ('Site.Pemeriksaan.View','Antrian.Pemeriksaan.View','Pemeriksaan.Pemeriksaan.View','Resep.Pemeriksaan.View'))
OR (r.nama_role='APOTEKER' AND p.nama_permission IN ('Site.Apotek.View','Site.Master.View','Site.Laporan.View','Resep.Apotek.View','Penjualan.Apotek.View','Stok.Apotek.View','Pengadaan.Apotek.View','Pengadaan.Master.View','Laporan.Laporan.View','lihat_laporan'))
ON CONFLICT DO NOTHING;

-- Bagian 5 : hapus permission View usang (context content, sudah pensiun)
DELETE FROM public.role_permissions WHERE id_permission IN
(SELECT id_permission FROM public.permissions WHERE nama_permission LIKE '%.Content.View' OR nama_permission='Site.Content.View');
DELETE FROM public.permissions WHERE nama_permission LIKE '%.Content.View' OR nama_permission='Site.Content.View';

-- Bagian 6 : seed portal pasien (hanya bila user id 5 ada & belum map) --
INSERT INTO public.pasien (no_rm, nama, jenis_kelamin, status, id_user)
SELECT 'RM-000001','Pasien Contoh','L','AKTIF',5
WHERE EXISTS (SELECT 1 FROM public.users WHERE id_user=5)
AND NOT EXISTS (SELECT 1 FROM public.pasien WHERE id_user=5);

-- Bagian 7 : sinkron sequence (MAX; aman di semua kondisi) --------------
SELECT setval(pg_get_serial_sequence('public.supplier','id_supplier'), COALESCE((SELECT MAX(id_supplier) FROM public.supplier), 1), false);
SELECT setval(pg_get_serial_sequence('public.pengadaan_obat','id_pengadaan'), COALESCE((SELECT MAX(id_pengadaan) FROM public.pengadaan_obat), 1), false);
SELECT setval(pg_get_serial_sequence('public.penerimaan_obat','id_penerimaan'), COALESCE((SELECT MAX(id_penerimaan) FROM public.penerimaan_obat), 1), false);
SELECT setval(pg_get_serial_sequence('public.retur_pengadaan','id_retur'), COALESCE((SELECT MAX(id_retur) FROM public.retur_pengadaan), 1), false);

-- Bagian 8 : APOTEK ONLINE (migrasi 004) ---------------------------------
CREATE TABLE IF NOT EXISTS public.pesanan_online (
    id_pesanan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pasien BIGINT NOT NULL REFERENCES public.pasien(id_pasien) ON UPDATE CASCADE ON DELETE RESTRICT,
    id_penjualan BIGINT REFERENCES public.penjualan_obat(id_penjualan) ON UPDATE CASCADE ON DELETE RESTRICT,
    id_tagihan BIGINT REFERENCES public.tagihan(id_tagihan) ON UPDATE CASCADE ON DELETE RESTRICT,
    nomor_pesanan VARCHAR(50) NOT NULL UNIQUE,
    tanggal_pesanan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    alamat_kirim TEXT NOT NULL,
    total NUMERIC(15,2) NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'MENUNGGU',
    status_bayar VARCHAR(20) NOT NULL DEFAULT 'BELUM_DIBAYAR',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_pesanan_status') THEN ALTER TABLE ONLY public.pesanan_online ADD CONSTRAINT chk_pesanan_status CHECK (status IN ('MENUNGGU','DIVERIFIKASI','DIPROSES','SIAP','SELESAI','BATAL')); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_pesanan_bayar') THEN ALTER TABLE ONLY public.pesanan_online ADD CONSTRAINT chk_pesanan_bayar CHECK (status_bayar IN ('BELUM_DIBAYAR','LUNAS','BATAL')); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_pesanan_total') THEN ALTER TABLE ONLY public.pesanan_online ADD CONSTRAINT chk_pesanan_total CHECK (total >= 0); END IF; END $$;
CREATE TABLE IF NOT EXISTS public.pesanan_online_detail (
    id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pesanan BIGINT NOT NULL REFERENCES public.pesanan_online(id_pesanan) ON UPDATE CASCADE ON DELETE CASCADE,
    id_obat BIGINT NOT NULL REFERENCES public.obat(id_obat) ON UPDATE CASCADE ON DELETE RESTRICT,
    id_resep BIGINT REFERENCES public.resep(id_resep) ON UPDATE CASCADE ON DELETE RESTRICT,
    jumlah INTEGER NOT NULL,
    harga NUMERIC(15,2) NOT NULL,
    subtotal NUMERIC(15,2) NOT NULL
);
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_pesanan_detail_jumlah') THEN ALTER TABLE ONLY public.pesanan_online_detail ADD CONSTRAINT chk_pesanan_detail_jumlah CHECK (jumlah > 0); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_pesanan_detail_harga') THEN ALTER TABLE ONLY public.pesanan_online_detail ADD CONSTRAINT chk_pesanan_detail_harga CHECK (harga >= 0); END IF; END $$;
DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_pesanan_detail_subtotal') THEN ALTER TABLE ONLY public.pesanan_online_detail ADD CONSTRAINT chk_pesanan_detail_subtotal CHECK (subtotal >= 0); END IF; END $$;
CREATE INDEX IF NOT EXISTS idx_pesanan_pasien ON public.pesanan_online(id_pasien);
CREATE INDEX IF NOT EXISTS idx_pesanan_status ON public.pesanan_online(status);
CREATE INDEX IF NOT EXISTS idx_pesanan_tanggal ON public.pesanan_online(tanggal_pesanan);
CREATE INDEX IF NOT EXISTS idx_pesanan_detail_pesanan ON public.pesanan_online_detail(id_pesanan);
-- Perluas jenis penjualan ONLINE (RESEP/LANGSUNG utuh).
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_jenis_penjualan') THEN ALTER TABLE public.penjualan_obat DROP CONSTRAINT chk_jenis_penjualan; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_jenis_penjualan') THEN ALTER TABLE public.penjualan_obat ADD CONSTRAINT chk_jenis_penjualan CHECK (jenis_penjualan IN ('RESEP','LANGSUNG','ONLINE')); END IF;
END $$;
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_penjualan_resep_relation' AND pg_get_constraintdef(oid) NOT LIKE '%ONLINE%') THEN ALTER TABLE public.penjualan_obat DROP CONSTRAINT chk_penjualan_resep_relation; END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'chk_penjualan_resep_relation') THEN ALTER TABLE public.penjualan_obat ADD CONSTRAINT chk_penjualan_resep_relation CHECK ((jenis_penjualan = 'RESEP' AND id_resep IS NOT NULL) OR (jenis_penjualan IN ('LANGSUNG','ONLINE'))); END IF;
END $$;
-- Permission apotek online.
INSERT INTO public.permissions (nama_permission, modul) VALUES
('belanja_online','APOTEK_ONLINE'),('kelola_pesanan_online','APOTEK_ONLINE'),
('Site.Online.View','MANAJEMEN_SISTEM'),('Apotekonline.Online.View','APOTEK_ONLINE'),
('Apotekonline.Apotek.View','APOTEK_ONLINE')
ON CONFLICT (nama_permission) DO NOTHING;
INSERT INTO public.role_permissions (id_role, id_permission)
SELECT r.id_role, p.id_permission FROM public.permissions p JOIN public.roles r ON
(r.nama_role='PASIEN' AND p.nama_permission IN ('belanja_online','Site.Online.View','Apotekonline.Online.View'))
OR (r.nama_role='APOTEKER' AND p.nama_permission IN ('kelola_pesanan_online','Apotekonline.Apotek.View'))
ON CONFLICT DO NOTHING;
SELECT setval(pg_get_serial_sequence('public.pesanan_online','id_pesanan'), COALESCE((SELECT MAX(id_pesanan) FROM public.pesanan_online), 1), false);
