-- ============================================================
-- SINKRON DB TEMAN: jalankan file ini SEKALI via Laragon DB
-- (HeidiSQL/TablePlus > pilih db apotek > jalankan query file ini).
-- Aman diulang: semua pakai IF NOT EXISTS / ON CONFLICT / guard.
-- Isi: 009 retur online + 010 sistem persediaan (termasuk kolom
-- batch & ED penerimaan yg dulu milik 008).
-- ============================================================

-- ---------- 009: retur online ----------
CREATE TABLE IF NOT EXISTS retur_online (
    id_retur BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pesanan BIGINT NOT NULL REFERENCES pesanan_online(id_pesanan) ON DELETE RESTRICT,
    nomor_retur VARCHAR(50) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL DEFAULT 'DIMINTA' CHECK (status IN ('DIMINTA','SELESAI','DITOLAK')),
    alasan TEXT NOT NULL,
    catatan_apoteker TEXT,
    metode_refund VARCHAR(20) CHECK (metode_refund IN ('TUNAI','TRANSFER','E_WALLET','LAINNYA')),
    nominal_refund NUMERIC(15,2) NOT NULL DEFAULT 0 CHECK (nominal_refund >= 0),
    tanggal_pengajuan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tanggal_keputusan TIMESTAMP,
    diproses_oleh BIGINT REFERENCES users(id_user),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS retur_online_detail (
    id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_retur BIGINT NOT NULL REFERENCES retur_online(id_retur) ON DELETE RESTRICT,
    id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
    jumlah INTEGER NOT NULL CHECK (jumlah > 0),
    disposisi VARCHAR(20) CHECK (disposisi IN ('RESTOCK','MUSNAH')),
    UNIQUE (id_retur, id_obat)
);

-- ---------- 010: master obat ----------
ALTER TABLE obat
    ADD COLUMN IF NOT EXISTS kategori character varying(100),
    ADD COLUMN IF NOT EXISTS bentuk_sediaan character varying(100),
    ADD COLUMN IF NOT EXISTS kandungan character varying(200),
    ADD COLUMN IF NOT EXISTS produsen character varying(150),
    ADD COLUMN IF NOT EXISTS id_supplier_utama BIGINT REFERENCES supplier(id_supplier),
    ADD COLUMN IF NOT EXISTS harga_satuan NUMERIC(15,2) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS harga_jual NUMERIC(15,2) NOT NULL DEFAULT 0;
UPDATE obat SET harga_satuan = harga WHERE harga_satuan = 0;
UPDATE obat SET harga_jual = harga WHERE harga_jual = 0;

-- ---------- 010: permintaan (tabel dulu, baru di-FK PO) ----------
CREATE TABLE IF NOT EXISTS permintaan_pengadaan (
    id_permintaan BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nomor_permintaan VARCHAR(50) NOT NULL UNIQUE,
    tanggal_permintaan TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_pemohon BIGINT REFERENCES users(id_user),
    unit VARCHAR(100) NOT NULL DEFAULT 'APOTEK',
    status VARCHAR(20) NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT','DIAJUKAN','DISETUJUI','DIPROSES','SELESAI','DITOLAK','DIBATALKAN')),
    catatan TEXT,
    disetujui_oleh BIGINT REFERENCES users(id_user),
    tanggal_persetujuan TIMESTAMP,
    catatan_persetujuan TEXT,
    dibuat_oleh BIGINT REFERENCES users(id_user),
    diubah_oleh BIGINT REFERENCES users(id_user),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS permintaan_pengadaan_detail (
    id_detail BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_permintaan BIGINT NOT NULL REFERENCES permintaan_pengadaan(id_permintaan) ON DELETE CASCADE,
    id_obat BIGINT NOT NULL REFERENCES obat(id_obat),
    satuan VARCHAR(50),
    harga_referensi NUMERIC(15,2) NOT NULL DEFAULT 0,
    stok_saat_minta INTEGER NOT NULL DEFAULT 0,
    jumlah_minta INTEGER NOT NULL CHECK (jumlah_minta > 0),
    catatan TEXT,
    UNIQUE (id_permintaan, id_obat)
);
CREATE TABLE IF NOT EXISTS permintaan_status_log (
    id_log BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_permintaan BIGINT NOT NULL REFERENCES permintaan_pengadaan(id_permintaan) ON DELETE CASCADE,
    status_lama VARCHAR(20),
    status_baru VARCHAR(20) NOT NULL,
    id_user BIGINT REFERENCES users(id_user),
    tanggal TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    catatan TEXT
);
CREATE INDEX IF NOT EXISTS idx_permintaan_status ON permintaan_pengadaan (status);
ALTER TABLE pengadaan_obat ADD COLUMN IF NOT EXISTS id_permintaan BIGINT REFERENCES permintaan_pengadaan(id_permintaan);

-- ---------- 010: penerimaan ----------
ALTER TABLE penerimaan_obat
    ADD COLUMN IF NOT EXISTS no_surat_jalan character varying(100),
    ADD COLUMN IF NOT EXISTS no_faktur character varying(100),
    ADD COLUMN IF NOT EXISTS id_penerima BIGINT REFERENCES users(id_user),
    ADD COLUMN IF NOT EXISTS catatan TEXT,
    ADD COLUMN IF NOT EXISTS status_konfirmasi VARCHAR(20) NOT NULL DEFAULT 'DIKONFIRMASI'
        CHECK (status_konfirmasi IN ('DRAFT','DIPERIKSA','DIKONFIRMASI','DIBATALKAN'));
ALTER TABLE penerimaan_obat_detail
    ADD COLUMN IF NOT EXISTS nomor_batch character varying(100),
    ADD COLUMN IF NOT EXISTS tanggal_kadaluarsa date;
CREATE INDEX IF NOT EXISTS idx_penerimaan_obat_detail_expiry ON penerimaan_obat_detail (tanggal_kadaluarsa);

-- ---------- 010: retur pembelian ----------
ALTER TABLE retur_pengadaan
    ADD COLUMN IF NOT EXISTS diproses_oleh BIGINT REFERENCES users(id_user),
    ADD COLUMN IF NOT EXISTS tanggal_keputusan TIMESTAMP;
ALTER TABLE retur_pengadaan_detail
    ADD COLUMN IF NOT EXISTS nomor_batch character varying(100),
    ADD COLUMN IF NOT EXISTS tanggal_kadaluarsa date;
UPDATE retur_pengadaan SET status = 'DIAJUKAN' WHERE status = 'Diajukan';

-- ---------- 010: stok batch + mutasi ----------
CREATE TABLE IF NOT EXISTS stok_batch (
    id_batch BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_obat BIGINT NOT NULL REFERENCES obat(id_obat) ON DELETE RESTRICT,
    nomor_batch VARCHAR(100),
    tanggal_kadaluarsa DATE,
    jumlah INTEGER NOT NULL DEFAULT 0 CHECK (jumlah >= 0),
    dibuat_oleh BIGINT REFERENCES users(id_user),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_stok_batch_obat ON stok_batch (id_obat);
CREATE INDEX IF NOT EXISTS idx_stok_batch_ed ON stok_batch (tanggal_kadaluarsa);
ALTER TABLE mutasi_stok
    ADD COLUMN IF NOT EXISTS id_batch BIGINT REFERENCES stok_batch(id_batch),
    ADD COLUMN IF NOT EXISTS saldo INTEGER,
    ADD COLUMN IF NOT EXISTS id_user BIGINT REFERENCES users(id_user);

-- ---------- 010: permission persediaan ----------
INSERT INTO permissions (nama_permission, modul) VALUES
    ('kelola_permintaan', 'PERSEDIAAN'),
    ('setujui_permintaan', 'PERSEDIAAN'),
    ('kelola_penerimaan', 'PERSEDIAAN'),
    ('konfirmasi_penerimaan', 'PERSEDIAAN'),
    ('kelola_retur_pembelian', 'PERSEDIAAN')
ON CONFLICT (nama_permission) DO NOTHING;
INSERT INTO role_permissions (id_role, id_permission)
    SELECT DISTINCT r.id_role, p.id_permission FROM roles r
    JOIN role_permissions rp ON rp.id_role = r.id_role
    JOIN permissions kelola ON kelola.id_permission = rp.id_permission AND kelola.nama_permission = 'kelola_pengadaan'
    JOIN permissions p ON p.nama_permission IN
        ('kelola_permintaan','setujui_permintaan','kelola_penerimaan','konfirmasi_penerimaan','kelola_retur_pembelian')
    WHERE NOT EXISTS (SELECT 1 FROM role_permissions x
        WHERE x.id_role = r.id_role AND x.id_permission = p.id_permission);
