<?php if (validation_errors()): ?><div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert">&times;</button><?php echo validation_errors(); ?></div><?php endif; ?>
<div class="row"><div class="col-md-12"><div class="card card-primary">
    <div class="card-header"><h3 class="card-title">Form Edit Obat</h3></div>
    <?php echo form_open($this->uri->uri_string()); ?><div class="card-body">
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="kode_obat">Kode Obat</label><input id="kode_obat" class="form-control" readonly value="<?php echo html_escape($obat->kode_obat ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="nama_obat">Nama Obat <span class="text-danger">*</span></label><input id="nama_obat" name="nama_obat" class="form-control" required value="<?php echo set_value('nama_obat', $obat->nama_obat ?? ''); ?>"><?php echo form_error('nama_obat'); ?></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="jenis_obat">Jenis Obat</label><input id="jenis_obat" name="jenis_obat" class="form-control" value="<?php echo set_value('jenis_obat', $obat->jenis_obat ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="satuan">Satuan <span class="text-danger">*</span></label><input id="satuan" name="satuan" class="form-control" required value="<?php echo set_value('satuan', $obat->satuan ?? ''); ?>"><?php echo form_error('satuan'); ?></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="harga">Harga <span class="text-danger">*</span></label><input id="harga" type="number" min="0" name="harga" class="form-control" required value="<?php echo set_value('harga', (int)($obat->harga ?? 0)); ?>"><?php echo form_error('harga'); ?></div></div><div class="col-md-6">
        <div class="form-group"><label for="stok_minimum">Stok Minimum</label><input id="stok_minimum" type="number" min="0" name="stok_minimum" class="form-control" value="<?php echo set_value('stok_minimum', (int)($obat->stok_minimum ?? 0)); ?>"></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="wajib_resep">Wajib Resep</label><select id="wajib_resep" name="wajib_resep" class="form-control select2"><option value="false" <?php echo !($obat->wajib_resep ?? false) ? 'selected' : ''; ?>>TIDAK</option><option value="true" <?php echo ($obat->wajib_resep ?? false) ? 'selected' : ''; ?>>YA</option></select></div></div><div class="col-md-6">
        <div class="form-group"><label for="status">Status</label><select id="status" name="status" class="form-control select2"><option value="AKTIF" <?php echo ($obat->status ?? '') === 'AKTIF' ? 'selected' : ''; ?>>AKTIF</option><option value="NONAKTIF" <?php echo ($obat->status ?? '') === 'NONAKTIF' ? 'selected' : ''; ?>>NONAKTIF</option></select></div></div></div>
    </div><div class="card-footer"><button type="submit" name="save" class="btn btn-primary">Simpan Perubahan</button><a href="<?php echo site_url(SITE_AREA . '/master/obat'); ?>" class="btn btn-default float-right">Batal</a></div><?php echo form_close(); ?>
</div></div></div>
