<?php // Form ubah obat (harga/satuan di sini merembet ke semua transaksi). ?>
<?php if (validation_errors()): ?><div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert">&times;</button><?php echo validation_errors(); ?></div><?php endif; ?>
<div class="row"><div class="col-md-12"><div class="card card-primary">
    <div class="card-header"><h3 class="card-title">Form Edit Obat</h3></div>
    <?php echo form_open($this->uri->uri_string()); ?><div class="card-body">
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="kode_obat">Kode Obat</label><input id="kode_obat" class="form-control" readonly value="<?php echo html_escape($obat->kode_obat ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="nama_obat">Nama Obat <span class="text-danger">*</span></label><input id="nama_obat" name="nama_obat" class="form-control" required value="<?php echo set_value('nama_obat', $obat->nama_obat ?? ''); ?>"><?php echo form_error('nama_obat'); ?></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="jenis_obat">Jenis Obat</label><input id="jenis_obat" name="jenis_obat" class="form-control" value="<?php echo set_value('jenis_obat', $obat->jenis_obat ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="id_satuan">Satuan <span class="text-danger">*</span></label><select id="id_satuan" name="id_satuan" class="form-control select2" required><option value="">-- Pilih Satuan --</option><?php foreach ($satuan_list as $s): ?><option value="<?php echo $s->id_satuan; ?>" <?php echo set_select('id_satuan', $s->id_satuan, (isset($obat->id_satuan) && $obat->id_satuan == $s->id_satuan)); ?>><?php echo html_escape($s->nama_satuan); ?></option><?php endforeach; ?></select><?php echo form_error('id_satuan'); ?></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="harga">Harga Satuan <span class="text-danger">*</span></label><input id="harga" type="number" min="0" name="harga" class="form-control" required value="<?php echo set_value('harga', (int)($obat->harga_satuan ?? $obat->harga ?? 0)); ?>"><?php echo form_error('harga'); ?><small class="form-text text-muted">Otomatis dipakai sebagai harga satuan transaksi.</small></div></div><div class="col-md-6">
        <div class="form-group"><label for="harga_jual">Harga Jual</label><input id="harga_jual" type="number" min="0" name="harga_jual" class="form-control" value="<?php echo set_value('harga_jual', (int)($obat->harga_jual ?? 0)); ?>"></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="kategori">Kategori</label><input id="kategori" name="kategori" class="form-control" maxlength="100" value="<?php echo set_value('kategori', $obat->kategori ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="bentuk_sediaan">Bentuk Sediaan</label><input id="bentuk_sediaan" name="bentuk_sediaan" class="form-control" maxlength="100" value="<?php echo set_value('bentuk_sediaan', $obat->bentuk_sediaan ?? ''); ?>"></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="kandungan">Kandungan</label><input id="kandungan" name="kandungan" class="form-control" maxlength="200" value="<?php echo set_value('kandungan', $obat->kandungan ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="produsen">Produsen</label><input id="produsen" name="produsen" class="form-control" maxlength="150" value="<?php echo set_value('produsen', $obat->produsen ?? ''); ?>"></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="id_supplier_utama">Supplier Utama</label><select id="id_supplier_utama" name="id_supplier_utama" class="form-control select2"><option value="">-- Tidak ada --</option><?php foreach ($supplier_list as $s): ?><option value="<?php echo $s->id_supplier; ?>"<?php echo (int)($obat->id_supplier_utama ?? 0) === (int) $s->id_supplier ? ' selected' : ''; ?>><?php echo html_escape($s->nama_supplier); ?></option><?php endforeach; ?></select></div></div><div class="col-md-6">
        <div class="form-group"><label for="stok_minimum">Stok Minimum</label><input id="stok_minimum" type="number" min="0" name="stok_minimum" class="form-control" value="<?php echo set_value('stok_minimum', (int)($obat->stok_minimum ?? 0)); ?>"></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="wajib_resep">Wajib Resep</label><select id="wajib_resep" name="wajib_resep" class="form-control select2"><option value="false" <?php echo !($obat->wajib_resep ?? false) ? 'selected' : ''; ?>>TIDAK</option><option value="true" <?php echo ($obat->wajib_resep ?? false) ? 'selected' : ''; ?>>YA</option></select></div></div><div class="col-md-6">
        <div class="form-group"><label for="status">Status</label><select id="status" name="status" class="form-control select2"><option value="AKTIF" <?php echo ($obat->status ?? '') === 'AKTIF' ? 'selected' : ''; ?>>AKTIF</option><option value="NONAKTIF" <?php echo ($obat->status ?? '') === 'NONAKTIF' ? 'selected' : ''; ?>>NONAKTIF</option></select></div></div></div>
    </div><div class="card-footer"><button type="submit" name="save" class="btn btn-primary">Simpan Perubahan</button><a href="<?php echo site_url(SITE_AREA . '/master/obat'); ?>" class="btn btn-default float-right">Batal</a></div><?php echo form_close(); ?>
</div></div></div>
