<?php if (validation_errors()): ?><div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert">&times;</button><?php echo validation_errors(); ?></div><?php endif; ?>
<div class="row"><div class="col-md-12"><div class="card card-primary">
    <div class="card-header"><h3 class="card-title">Form Edit Pasien</h3></div>
    <?php echo form_open($this->uri->uri_string()); ?><div class="card-body">
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="no_rm">Nomor Rekam Medis</label><input id="no_rm" class="form-control" readonly value="<?php echo html_escape($pasien->no_rm ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="nama">Nama <span class="text-danger">*</span></label><input id="nama" name="nama" class="form-control" required value="<?php echo set_value('nama', $pasien->nama ?? ''); ?>"><?php echo form_error('nama'); ?></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="nik">NIK</label><input id="nik" name="nik" class="form-control" maxlength="20" value="<?php echo set_value('nik', $pasien->nik ?? ''); ?>"><?php echo form_error('nik'); ?></div></div><div class="col-md-6">
        <div class="form-group"><label for="tanggal_lahir">Tanggal Lahir</label><input id="tanggal_lahir" type="date" name="tanggal_lahir" class="form-control" value="<?php echo set_value('tanggal_lahir', $pasien->tanggal_lahir ?? ''); ?>"></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="jenis_kelamin">Jenis Kelamin</label><select id="jenis_kelamin" name="jenis_kelamin" class="form-control select2"><option value="">-- Pilih --</option><option value="L" <?php echo ($pasien->jenis_kelamin ?? '') === 'L' ? 'selected' : ''; ?>>Laki-laki</option><option value="P" <?php echo ($pasien->jenis_kelamin ?? '') === 'P' ? 'selected' : ''; ?>>Perempuan</option></select></div></div></div>
        <div class="form-group"><label for="alamat">Alamat</label><textarea id="alamat" name="alamat" class="form-control" rows="3"><?php echo set_value('alamat', $pasien->alamat ?? ''); ?></textarea></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="no_hp">No. HP</label><input id="no_hp" name="no_hp" class="form-control" value="<?php echo set_value('no_hp', $pasien->no_hp ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="status">Status</label><select id="status" name="status" class="form-control select2"><option value="AKTIF" <?php echo ($pasien->status ?? '') === 'AKTIF' ? 'selected' : ''; ?>>AKTIF</option><option value="NONAKTIF" <?php echo ($pasien->status ?? '') === 'NONAKTIF' ? 'selected' : ''; ?>>NONAKTIF</option></select></div></div></div>
    </div><div class="card-footer"><button type="submit" name="save" class="btn btn-primary">Simpan Perubahan</button><a href="<?php echo site_url(SITE_AREA . '/' . $this->uri->segment(2) . '/' . $this->uri->segment(3)); ?>" class="btn btn-default float-right">Batal</a></div><?php echo form_close(); ?>
</div></div></div>
