<?php if (validation_errors()): ?><div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert">&times;</button><?php echo validation_errors(); ?></div><?php endif; ?>
<div class="row"><div class="col-md-12"><div class="card card-primary">
    <div class="card-header"><h3 class="card-title">Form Edit Dokter</h3></div>
    <?php echo form_open($this->uri->uri_string()); ?><div class="card-body">
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="nama_dokter">Nama Dokter <span class="text-danger">*</span></label><input id="nama_dokter" name="nama_dokter" class="form-control" required value="<?php echo set_value('nama_dokter', $dokter->nama_dokter ?? ''); ?>"><?php echo form_error('nama_dokter'); ?></div></div><div class="col-md-6">
        <div class="form-group"><label for="id_spesialis">Spesialis</label><select id="id_spesialis" name="id_spesialis" class="form-control select2"><option value="">-- Pilih Spesialis --</option><?php foreach ($spesialis_list as $s): ?><option value="<?php echo $s->id_spesialis; ?>" <?php echo ($dokter->id_spesialis ?? '') == $s->id_spesialis ? 'selected' : ''; ?>><?php echo html_escape($s->nama_spesialis); ?></option><?php endforeach; ?></select></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="no_sip">No. SIP</label><input id="no_sip" name="no_sip" class="form-control" value="<?php echo set_value('no_sip', $dokter->no_sip ?? ''); ?>"></div></div><div class="col-md-6">
        <div class="form-group"><label for="no_hp">No. HP</label><input id="no_hp" name="no_hp" class="form-control" value="<?php echo set_value('no_hp', $dokter->no_hp ?? ''); ?>"></div></div></div>
        <div class="row"><div class="col-md-6"><div class="form-group"><label for="tarif">Tarif (Rp) <span class="text-danger">*</span></label><input id="tarif" type="number" min="0" name="tarif" class="form-control" required value="<?php echo set_value('tarif', (int)($dokter->tarif ?? 0)); ?>"><?php echo form_error('tarif'); ?></div></div><div class="col-md-6">
        <div class="form-group"><label for="status">Status</label><select id="status" name="status" class="form-control select2"><option value="AKTIF" <?php echo ($dokter->status ?? '') === 'AKTIF' ? 'selected' : ''; ?>>AKTIF</option><option value="NONAKTIF" <?php echo ($dokter->status ?? '') === 'NONAKTIF' ? 'selected' : ''; ?>>NONAKTIF</option></select></div></div></div>
    </div><div class="card-footer"><button type="submit" name="save" class="btn btn-primary">Simpan Perubahan</button><a href="<?php echo site_url(SITE_AREA . '/master/dokter'); ?>" class="btn btn-default float-right">Batal</a></div><?php echo form_close(); ?>
</div></div></div>
