<?php if (validation_errors()): ?><div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert">&times;</button><?php echo validation_errors(); ?></div><?php endif; ?>
<div class="row"><div class="col-md-12"><div class="card card-primary"><div class="card-header"><h3 class="card-title">Form Pemeriksaan</h3></div>
<?php echo form_open($this->uri->uri_string()); ?><div class="card-body">
<div class="row"><div class="col-md-6"><div class="form-group"><label for="id_kunjungan">Kunjungan <span class="text-danger">*</span></label><select id="id_kunjungan" name="id_kunjungan" class="form-control select2" required><option value="">-- Pilih Kunjungan --</option><?php foreach($kunjungan_list as $k): ?><option value="<?php echo $k->id_kunjungan; ?>"><?php echo html_escape($k->no_rm . ' - ' . $k->nama_pasien . ' - ' . $k->nama_dokter); ?></option><?php endforeach; ?></select><?php echo form_error('id_kunjungan'); ?></div></div><div class="col-md-6">
<div class="form-group"><label for="id_dokter">Dokter <span class="text-danger">*</span></label><?php if (isset($dokter_terkunci)): ?><input type="hidden" name="id_dokter" value="<?php echo (int) $dokter_terkunci; ?>"><input type="text" class="form-control" value="<?php echo html_escape(isset($dokter_list[0]) ? $dokter_list[0]->nama_dokter : ''); ?>" readonly><?php else: ?><select id="id_dokter" name="id_dokter" class="form-control select2" required><option value="">-- Pilih Dokter --</option><?php foreach($dokter_list as $d): ?><option value="<?php echo $d->id_dokter; ?>"><?php echo html_escape($d->nama_dokter); ?></option><?php endforeach; ?></select><?php endif; ?><?php echo form_error('id_dokter'); ?></div></div></div>
<div class="form-group"><label for="keluhan">Keluhan</label><textarea id="keluhan" name="keluhan" class="form-control" rows="3"><?php echo set_value('keluhan'); ?></textarea></div>
<div class="form-group"><label for="hasil_pemeriksaan">Hasil Pemeriksaan</label><textarea id="hasil_pemeriksaan" name="hasil_pemeriksaan" class="form-control" rows="3"><?php echo set_value('hasil_pemeriksaan'); ?></textarea></div>
<div class="form-group"><label for="catatan_dokter">Catatan Dokter</label><textarea id="catatan_dokter" name="catatan_dokter" class="form-control" rows="3"><?php echo set_value('catatan_dokter'); ?></textarea></div>
</div><div class="card-footer"><button type="submit" name="save" class="btn btn-primary">Simpan</button><a href="<?php echo site_url(SITE_AREA . '/' . $this->uri->segment(2) . '/' . $this->uri->segment(3)); ?>" class="btn btn-default float-right">Batal</a></div><?php echo form_close(); ?></div></div></div>
